"""Add CAPA exam prep content to argo.html chapters."""
import re

with open('argo.html', 'r', encoding='utf-8') as f:
    content = f.read()

# Content blocks - using proper string formatting to avoid syntax errors
EXAM_TIPS = {
    "Ch2": """                    <div class="ckad-exam-tip"><h5>CAPA Exam: K8s Prerequisites Are Implicitly Tested</h5><p>While CAPA doesn't directly ask "What is a Pod?", it assumes you can read and write YAML for K8s objects. You'll encounter Pod specs inside Workflow templates, Service definitions in Rollout configs, and ConfigMaps/Secrets everywhere. Key areas to be fluent in: labels & selectors (how Services find Pods), namespaces (Argo CD deploys to specific namespaces), and CRDs (Argo IS a set of CRDs). If you can't read a Deployment YAML at a glance, practice with <code>kubectl explain</code> before exam day.</p></div>
                    <div class="ckad-gotcha"><h5>Common CAPA Mistakes — Chapter 2</h5><ul><li><strong>YAML indentation errors:</strong> Argo is STRICT about YAML. One tab character or wrong indentation level causes silent failures. Always use spaces (2 per level), never tabs. Use <code>yamllint</code> or your IDE's YAML validator.</li><li><strong>Confusing labels vs annotations:</strong> Labels are for K8s selectors (used by Services, Deployments). Annotations are for tool metadata (Argo CD uses annotations like <code>argocd.argoproj.io/sync-options</code>). They're NOT interchangeable — selectors use labels only.</li><li><strong>Forgetting CRDs extend the API:</strong> When Argo is installed, it teaches K8s new resource types. <code>kubectl api-resources | grep argo</code> shows them all. A Workflow is as real as a Pod to the API server.</li></ul></div>""",
    "Ch3": """                    <div class="ckad-gotcha"><h5>Common CAPA Mistakes — Chapter 3</h5><ul><li><strong>Wrong namespace:</strong> Argo CD components MUST be in <code>argocd</code> namespace (unless explicitly configured otherwise). Installing elsewhere breaks default RBAC and network configurations.</li><li><strong>Forgetting to change the admin password:</strong> The initial password is in a K8s Secret. The exam may test: <code>kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d</code>.</li><li><strong>Port-forward gotcha:</strong> argocd-server serves on port 443 (HTTPS), not 80. <code>kubectl port-forward svc/argocd-server -n argocd 8080:443</code> — notice the 443.</li><li><strong>Non-HA vs HA install:</strong> The quick-start manifest is a single YAML for development/testing. HA/production requires separate manifests with replicas > 1 and external Redis/Postgres.</li></ul></div>""",
    "Ch4": """                    <div class="ckad-gotcha"><h5>Common CAPA Mistakes — Chapter 4</h5><ul><li><strong>Confusing sync status with health status:</strong> An app can be "Synced" (cluster matches Git) but "Degraded" (pod is crashing). Sync is about configuration; health is about runtime behavior. These are independent dimensions.</li><li><strong>Auto-sync without pruning:</strong> If you enable automated sync but NOT pruning, deleted resources in Git remain in the cluster. Always pair auto-sync with <code>prune: true</code> for true GitOps.</li><li><strong>Source type detection:</strong> Argo CD auto-detects source type (Helm, Kustomize, directory) based on files present. If detection fails, explicitly set <code>source.type</code>.</li><li><strong>Multiple sources order matters:</strong> When using multiple sources, the first source is the "main" one for parameter resolution.</li></ul></div>""",
    "Ch5": """                    <div class="ckad-gotcha"><h5>Common CAPA Mistakes — Chapter 5</h5><ul><li><strong>Default project is wide open:</strong> Every new Application is in the "default" project unless specified otherwise. The default project has NO restrictions — any repo, any cluster, any namespace. For production, always create dedicated AppProjects.</li><li><strong>Allow-list mentality:</strong> AppProjects use ALLOW lists for source repos, destinations, and cluster resources. If you don't whitelist it, it's blocked. An empty whitelist blocks everything — including valid resources.</li><li><strong>Orphaned resources:</strong> Deleting an AppProject does NOT delete its Applications — they become orphaned. Migrate Applications to a new project before deleting the old one.</li></ul></div>""",
    "Ch6": """                    <div class="ckad-gotcha"><h5>Common CAPA Mistakes — Chapter 6</h5><ul><li><strong>Sync wave numbers:</strong> LOWER numbers deploy FIRST. Wave -1 runs before wave 0, which runs before wave 5. Resources without a wave annotation run LAST. Remember: negative numbers = earliest.</li><li><strong>ApplicationSet generators confusion:</strong> List generator = static list. Cluster generator = auto-discovers clusters. Git generator = reads from Git directories/files. Matrix generator = combines two generators. Don't mix up their use cases.</li><li><strong>Notifications need BOTH trigger AND template:</strong> A trigger without a template produces no output. Both must be configured in <code>argocd-notifications-cm</code> ConfigMap.</li></ul></div>""",
    "Ch7": """                    <div class="ckad-gotcha"><h5>Common CAPA Mistakes — Chapter 7</h5><ul><li><strong>Mixing app code and deployment config:</strong> Best practice is SEPARATE repos — one for application source code, another for deployment configs (GitOps repo). Mixing them creates noise in Git history and blurs ownership.</li><li><strong>Kustomize overlay inheritance:</strong> Overlays inherit from base and PATCH (not replace). If you want to replace a base resource entirely, use a strategic merge patch that sets all fields.</li><li><strong>Secrets in Git:</strong> NEVER store plaintext secrets in your GitOps repo. Use Sealed Secrets, External Secrets Operator, or SOPS with KMS encryption.</li></ul></div>""",
    "Ch8": """                    <div class="ckad-gotcha"><h5>Common CAPA Mistakes — Chapter 8</h5><ul><li><strong>Forgetting --grpc-web flag:</strong> Some environments (especially behind certain proxies) need <code>argocd login --grpc-web</code>. If login fails, try this flag before troubleshooting further.</li><li><strong>Sync vs Hard Refresh:</strong> <code>argocd app sync</code> deploys changes. <code>argocd app get --refresh hard</code> rescans Git but doesn't deploy. They serve different purposes.</li><li><strong>Delete without cascade:</strong> <code>argocd app delete APP</code> only removes the Application CRD. Add <code>--cascade</code> to also delete all deployed K8s resources. Without cascade, resources become orphaned.</li></ul></div>""",
    "Ch13": """                    <div class="ckad-gotcha"><h5>Common CAPA Mistakes — Chapter 13</h5><ul><li><strong>Retry vs Resubmit:</strong> <code>argo retry</code> retries from the FAILED step (preserving successful steps). <code>argo resubmit</code> restarts the ENTIRE workflow from scratch. Know the difference — the exam will test it.</li><li><strong>TTL cleanup:</strong> Without <code>ttlStrategy</code>, completed workflow pods accumulate forever. Set <code>secondsAfterCompletion: 3600</code> to auto-clean after 1 hour. On a busy cluster, this prevents resource exhaustion.</li><li><strong>Pending pods:</strong> If a workflow step is stuck "Pending", check in order: node resources, taints/tolerations, PVC binding, image pull errors, namespace resource quotas.</li></ul></div>""",
    "Ch15": """                    <div class="ckad-gotcha"><h5>Common CAPA Mistakes — Chapter 15</h5><ul><li><strong>Service selector must match pod labels:</strong> The Rollout's pod template labels MUST match the Service selector. If they don't, traffic won't reach pods. The Rollout controller manages this automatically — don't manually edit the Service.</li><li><strong>Blue-Green activeService:</strong> This Service ALWAYS points to the live version. The Rollout swaps which ReplicaSet it points to during promotion. The previewService lets you test before switching.</li><li><strong>Missing AnalysisTemplate:</strong> If you reference an AnalysisTemplate in canary steps that doesn't exist, the canary gets stuck waiting forever. Verify the template name and namespace match exactly.</li></ul></div>""",
    "Ch16": """                    <div class="ckad-gotcha"><h5>Common CAPA Mistakes — Chapter 16</h5><ul><li><strong>Rollout vs Argo CD sync order:</strong> Argo CD should sync the Rollout CRD, THEN the Rollout controller starts the canary/blue-green. These are sequential — if Argo CD syncs and the controller hasn't started, the Rollout appears stuck.</li><li><strong>:latest tag danger:</strong> Never use <code>:latest</code> tag in a Rollout. The controller needs SPECIFIC tags to differentiate stable from canary ReplicaSets. <code>:latest</code> = ambiguous version tracking.</li><li><strong>Undo after promotion:</strong> <code>argo rollouts undo</code> works even after full promotion. It reverts to the PREVIOUS ReplicaSet spec, not the original one.</li></ul></div>""",
    "Ch17": """                    <div class="ckad-gotcha"><h5>Common CAPA Mistakes — Chapter 17</h5><ul><li><strong>EventBus is required:</strong> Argo Events won't work without an EventBus. If events aren't flowing, check <code>kubectl get eventbus -n argo-events</code> first. The EventBus runs NATS — if it's not Ready, nothing works.</li><li><strong>Sensor RBAC:</strong> The Sensor's ServiceAccount needs permissions to create the resources it triggers (Workflows, HTTP calls). Missing RBAC = silent trigger failure with no obvious error.</li><li><strong>Event deduplication:</strong> Sensors track processed event IDs. If the same event is re-delivered (NATS retry), the Sensor ignores it — preventing duplicate workflow triggers.</li></ul></div>""",
    "Ch18": """                    <div class="ckad-gotcha"><h5>Common CAPA Mistakes — Chapter 18</h5><ul><li><strong>Calendar vs CronWorkflow:</strong> Calendar EventSource is MORE flexible (one schedule triggers multiple workflows via Sensor). But CronWorkflow is SIMPLER (single YAML). Use Calendar when you need to trigger multiple things from one schedule.</li><li><strong>Webhook path collisions:</strong> Each webhook EventSource needs a unique endpoint path. Two EventSources on the same path will conflict.</li><li><strong>GitHub webhook auto-registration:</strong> If the GitHub token has insufficient permissions, the EventSource deploys successfully but webhooks aren't created. Check Sensor logs for clues.</li></ul></div>""",
    "Ch19": """                    <div class="ckad-gotcha"><h5>Common CAPA Mistakes — Chapter 19</h5><ul><li><strong>Infinite CI loops:</strong> If the CI workflow commits back to the same Git repo, the commit triggers another CI run. Add an event filter to ignore commits from the CI bot user.</li><li><strong>Parameter extraction path:</strong> Event data is nested JSON. <code>dataKey: body.ref</code> extracts <code>ref</code> from the <code>body</code> object. Wrong path = empty parameter = failed workflow.</li><li><strong>Sensor trigger ordering:</strong> Multiple triggers in a Sensor execute SEQUENTIALLY by default. For parallel execution, use separate Sensors or the trigger policy field.</li></ul></div>""",
    "Ch20": """                    <div class="ckad-gotcha"><h5>Common CAPA Mistakes — Chapter 20</h5><ul><li><strong>Tight coupling fallacy:</strong> Each Argo component is independent. If one fails (e.g., Events), others may continue unaware (Argo CD still syncs). Always add monitoring at each stage — a broken pipeline link doesn't always produce obvious errors.</li><li><strong>Multiple sources of truth:</strong> The GitOps repo must be the ONE place where desired state is defined. If you update both the GitOps repo AND the cluster directly, Argo CD will detect drift and may revert your manual changes.</li><li><strong>Cross-cutting secrets:</strong> All 4 Argo projects need secrets (registry creds, Git tokens, DB passwords). Centralize with External Secrets Operator or Vault — don't duplicate secrets across components.</li></ul></div>""",
    "Ch21": """                    <div class="ckad-gotcha"><h5>Common CAPA Mistakes — Chapter 21</h5><ul><li><strong>Image Updater overrides Git:</strong> If Image Updater writes to Git directly, it bypasses your PR/code review process. Configure it to create PRs instead of direct commits for production environments.</li><li><strong>Helm vs Kustomize for GitOps:</strong> Helm templates are harder to read in Git (Go templates, not final YAML). Kustomize overlays are pure YAML — easier for GitOps diffing. CAPA favors Kustomize for GitOps scenarios.</li><li><strong>Progressive sync vs progressive delivery:</strong> Argo CD's sync waves control deployment ORDER. Argo Rollouts control traffic SPLITTING. They solve different problems — don't confuse them.</li></ul></div>""",
    "Ch22": """                    <div class="ckad-gotcha"><h5>Common CAPA Mistakes — Chapter 22</h5><ul><li><strong>Disabling admin without SSO:</strong> If you set <code>admin.enabled: false</code> in argocd-cm without configuring SSO first, you'll lock yourself out of Argo CD completely. Always verify SSO login works before disabling local admin.</li><li><strong>No resource limits:</strong> Argo CD components without CPU/memory limits can OOMKill during large syncs. Repo Server: 512Mi-1Gi. Application Controller: 1-2Gi. Redis: 256Mi-512Mi.</li><li><strong>Skipping minor versions during upgrade:</strong> Going from 2.8 to 2.11 can break CRD compatibility. Always upgrade ONE minor version at a time and test in staging first.</li></ul></div>""",
}

# Find all chapter starts
chapter_starts = [(m.group(1), m.start()) for m in re.finditer(r'CHAPTER (\d+):', content)]
print(f"Found {len(chapter_starts)} chapters")

# Process in reverse to maintain positions
added_count = 0
for i in range(len(chapter_starts) - 1, -1, -1):
    ch_num = chapter_starts[i][0]
    ch_start = chapter_starts[i][1]
    
    if i < len(chapter_starts) - 1:
        ch_end = chapter_starts[i + 1][1]
    else:
        ch_end = len(content)
    
    ch_label = f"Ch{ch_num}"
    if ch_label not in EXAM_TIPS:
        continue
    
    # Find the learning-objectives closing and insert exam content after it
    # Pattern: </div>\n\n                <!-- X.Y
    lo_match = re.search(
        r'(<div class="learning-objectives">.*?</div>)',
        content[ch_start:ch_end],
        re.DOTALL
    )
    
    if lo_match:
        insert_pos = ch_start + lo_match.end()
        section = content[ch_start:ch_end]
        
        # Check if content already exists
        if 'ckad-gotcha' not in section[:2000]:
            new_text = '\n' + EXAM_TIPS[ch_label] + '\n'
            content = content[:insert_pos] + new_text + content[insert_pos:]
            added_count += 1

print(f"Added content to {added_count} chapters")

with open('argo.html', 'w', encoding='utf-8') as f:
    f.write(content)

print("Done!")
