#!/usr/bin/env python3
"""Insert all 42 missing MCQs into cilium-test-prep.html"""

import re

HTML_PATH = r"c:\Users\owner\Desktop\DEV-DOCs\KUBERNETES\cilium-test-prep.html"

# =============================================================================
# BATCH 1: Q137–Q148 (Cat 5: Installation & Configuration)
# Subsections: 5.2 Helm & Config (Q137–Q142), 5.3 Upgrades & Ops (Q143–Q148)
# =============================================================================
MCQS_CAT5 = r"""
    <!-- ═══════════ 5.2: Helm & Config (Q137–Q142) ═══════════ -->
    <div class="section-block" id="cat5-2"><h3>5.2 Helm &amp; Config (Q137–Q142)</h3>

    <div class="mcq-block" id="q137" data-correct="B"><div class="mcq-number"><span class="domain-pill d5">Installation</span> Q137 of 200</div><div class="mcq-question">Helm chart repo for Cilium?</div><div class="mcq-options"><div class="mcq-option">A) https://helm.cilium.io/stable</div><div class="mcq-option">B) helm repo add cilium https://helm.cilium.io/ ; helm install cilium cilium/cilium --namespace kube-system</div><div class="mcq-option">C) helm install cilium stable/cilium</div><div class="mcq-option">D) Only via Cilium CLI, no Helm</div></div><button class="mcq-toggle-btn" onclick="toggleAnswer('a137')">👁️ Show Answer &amp; Explanation</button><div class="mcq-answer" id="a137"><div class="answer-label">✅ Correct Answer: B</div><p>Official Helm chart at https://helm.cilium.io/. Update: `helm repo update cilium`. Search versions: `helm search repo cilium/cilium --versions`.</p></div></div>

    <div class="mcq-block" id="q138" data-correct="C"><div class="mcq-number"><span class="domain-pill d5">Installation</span> Q138 of 200</div><div class="mcq-question">Helm values: kubeProxyReplacement options?</div><div class="mcq-options"><div class="mcq-option">A) true/false only</div><div class="mcq-option">B) enabled/disabled</div><div class="mcq-option">C) "disabled" (default), "partial" (ClusterIP only), "strict" (all services including NodePort). Strict needs: native devices, kernel 5.10+, eBPF Host Routing</div><div class="mcq-option">D) automatic detection only</div></div><button class="mcq-toggle-btn" onclick="toggleAnswer('a138')">👁️ Show Answer &amp; Explanation</button><div class="mcq-answer" id="a138"><div class="answer-label">✅ Correct Answer: C</div><p>Strict = full kube-proxy replacement with eBPF. Magic: `--set kubeProxyReplacement=strict`. NodePort, ExternalIPs, HostPort all via eBPF.</p></div></div>

    <div class="mcq-block" id="q139" data-correct="A"><div class="mcq-number"><span class="domain-pill d5">Installation</span> Q139 of 200</div><div class="mcq-question">ipam.mode values and when to use each?</div><div class="mcq-options"><div class="mcq-option">A) kubernetes (default, uses podCIDR), cluster-pool (Cilium-managed CIDR pool, best for self-managed), eni (AWS), azure (Azure), multi-pool (multiple CIDRs for multi-tenant)</div><div class="mcq-option">B) Only kubernetes and cluster-pool</div><div class="mcq-option">C) Only cloud-specific modes</div><div class="mcq-option">D) dhcp mode for all environments</div></div><button class="mcq-toggle-btn" onclick="toggleAnswer('a139')">👁️ Show Answer &amp; Explanation</button><div class="mcq-answer" id="a139"><div class="answer-label">✅ Correct Answer: A</div><p>cluster-pool: `--set ipam.mode=cluster-pool --set ipam.operator.clusterPoolIPv4PodCIDRList=10.0.0.0/8`. Good for bare metal. eni/azure: cloud-native IPAM.</p></div></div>

    <div class="mcq-block" id="q140" data-correct="D"><div class="mcq-number"><span class="domain-pill d5">Installation</span> Q140 of 200</div><div class="mcq-question">routingMode and tunnel settings?</div><div class="mcq-options"><div class="mcq-option">A) Always use VXLAN</div><div class="mcq-option">B) Always use native routing</div><div class="mcq-option">C) Only Geneve is supported</div><div class="mcq-option">D) tunnel: "vxlan" (default, overlay), "geneve", "disabled" (native routing, needs router BGP/static routes). routingMode: "native" (direct L3), "tunnel" (encapsulation). Auto-detected per cloud</div></div><button class="mcq-toggle-btn" onclick="toggleAnswer('a140')">👁️ Show Answer &amp; Explanation</button><div class="mcq-answer" id="a140"><div class="answer-label">✅ Correct Answer: D</div><p>Native: pods directly routable, better performance, needs route distribution. Tunnel: works anywhere, slight overhead. Cloud defaults: EKS=eni, GKE=geneve, AKS=azure.</p></div></div>

    <div class="mcq-block" id="q141" data-correct="B"><div class="mcq-number"><span class="domain-pill d5">Installation</span> Q141 of 200</div><div class="mcq-question">encryption.enabled + encryption.type values?</div><div class="mcq-options"><div class="mcq-option">A) Only WireGuard</div><div class="mcq-option">B) encryption.enabled=true + encryption.type="wireguard" (kernel 5.6+) OR "ipsec" (any kernel, more CPU). WireGuard: simpler, faster. IPSec: broader kernel support, more complex config</div><div class="mcq-option">C) TLS-based encryption only</div><div class="mcq-option">D) Encryption not supported in Cilium</div></div><button class="mcq-toggle-btn" onclick="toggleAnswer('a141')">👁️ Show Answer &amp; Explanation</button><div class="mcq-answer" id="a141"><div class="answer-label">✅ Correct Answer: B</div><p>WireGuard: kernel 5.6+, port 51871, simpler key management. IPSec: any kernel, uses XFRM, more CPU overhead. Both transparent to pods.</p></div></div>

    <div class="mcq-block" id="q142" data-correct="C"><div class="mcq-number"><span class="domain-pill d5">Installation</span> Q142 of 200</div><div class="mcq-question">Helm --set vs --values for production?</div><div class="mcq-options"><div class="mcq-option">A) --set only — simpler</div><div class="mcq-option">B) No difference</div><div class="mcq-option">C) --values values.yaml for production (GitOps, version controlled, reproducible). --set for quick overrides/dev. Best: ArgoCD/Flux with values.yaml in Git</div><div class="mcq-option">D) Production uses CLI only</div></div><button class="mcq-toggle-btn" onclick="toggleAnswer('a142')">👁️ Show Answer &amp; Explanation</button><div class="mcq-answer" id="a142"><div class="answer-label">✅ Correct Answer: C</div><p>GitOps pattern: store values.yaml in Git, ArgoCD syncs. Never `--set` in production — no audit trail, not reproducible. One values.yaml for each cluster.</p></div></div>
    </div>

    <!-- ═══════════ 5.3: Upgrades & Ops (Q143–Q148) ═══════════ -->
    <div class="section-block" id="cat5-3"><h3>5.3 Upgrades &amp; Ops (Q143–Q148)</h3>

    <div class="mcq-block" id="q143" data-correct="A"><div class="mcq-number"><span class="domain-pill d5">Installation</span> Q143 of 200</div><div class="mcq-question">Pre-upgrade checks for Cilium?</div><div class="mcq-options"><div class="mcq-option">A) Read upgrade notes (BREAKING CHANGES), check CRD schema required updates, verify Helm values deprecated keys, run cilium connectivity test BEFORE, check kernel compatibility with new version, backup etcd/CRDs</div><div class="mcq-option">B) Just run cilium upgrade</div><div class="mcq-option">C) Only check kernel version</div><div class="mcq-option">D) No checks needed — seamless</div></div><button class="mcq-toggle-btn" onclick="toggleAnswer('a143')">👁️ Show Answer &amp; Explanation</button><div class="mcq-answer" id="a143"><div class="answer-label">✅ Correct Answer: A</div><p>ALWAYS read upgrade notes first. Breaking changes between minors. CRD schema changes require `kubectl apply -f` before Helm upgrade. Run connectivity test pre-upgrade for baseline.</p></div></div>

    <div class="mcq-block" id="q144" data-correct="B"><div class="mcq-number"><span class="domain-pill d5">Installation</span> Q144 of 200</div><div class="mcq-question">Rolling back a Cilium upgrade?</div><div class="mcq-options"><div class="mcq-option">A) Impossible — must reinstall cluster</div><div class="mcq-option">B) `helm rollback cilium` — but eBPF programs may be NEWER than agent. If CRD schema changed, must also revert CRDs. Test rollback in staging first</div><div class="mcq-option">C) Just reinstall old version</div><div class="mcq-option">D) Cilium auto-rollback on failure</div></div><button class="mcq-toggle-btn" onclick="toggleAnswer('a144')">👁️ Show Answer &amp; Explanation</button><div class="mcq-answer" id="a144"><div class="answer-label">✅ Correct Answer: B</div><p>Key risk: eBPF programs loaded by new agent may not be understood by old agent. Solution: restart pods to reload eBPF programs. Always test rollback in staging.</p></div></div>

    <div class="mcq-block" id="q145" data-correct="C"><div class="mcq-number"><span class="domain-pill d5">Installation</span> Q145 of 200</div><div class="mcq-question">Cilium agent DaemonSet upgrade strategy?</div><div class="mcq-options"><div class="mcq-option">A) Recreate — all pods restart at once</div><div class="mcq-option">B) OnDelete only</div><div class="mcq-option">C) RollingUpdate (default). eBPF programs persist in kernel during restart — connections survive. Max unavailable: 2 or 10%. Node-by-node, 30s wait between nodes</div><div class="mcq-option">D) Blue/Green deployment</div></div><button class="mcq-toggle-btn" onclick="toggleAnswer('a145')">👁️ Show Answer &amp; Explanation</button><div class="mcq-answer" id="a145"><div class="answer-label">✅ Correct Answer: C</div><p>DaemonSet uses RollingUpdate. Key: eBPF programs stay loaded in kernel while agent restarts. Existing connections survive. New connections use new agent.</p></div></div>

    <div class="mcq-block" id="q146" data-correct="A"><div class="mcq-number"><span class="domain-pill d5">Installation</span> Q146 of 200</div><div class="mcq-question">cilium config vs cilium-config ConfigMap?</div><div class="mcq-options"><div class="mcq-option">A) `cilium config` reads/writes the cilium-config ConfigMap in kube-system. Runtime changes via `cilium config set Key=Value`. Persistent across agent restarts</div><div class="mcq-option">B) Two separate config systems</div><div class="mcq-option">C) ConfigMap is deprecated — use CLI only</div><div class="mcq-option">D) CLI config is local only, not cluster-wide</div></div><button class="mcq-toggle-btn" onclick="toggleAnswer('a146')">👁️ Show Answer &amp; Explanation</button><div class="mcq-answer" id="a146"><div class="answer-label">✅ Correct Answer: A</div><p>`cilium config` is a convenience wrapper around the ConfigMap. Changes propagate to all agents. `cilium config view` shows current runtime config.</p></div></div>

    <div class="mcq-block" id="q147" data-correct="D"><div class="mcq-number"><span class="domain-pill d5">Installation</span> Q147 of 200</div><div class="mcq-question">Uninstall Cilium cleanly?</div><div class="mcq-options"><div class="mcq-option">A) kubectl delete ns kube-system</div><div class="mcq-option">B) helm uninstall cilium — done</div><div class="mcq-option">C) Just delete the DaemonSet</div><div class="mcq-option">D) `cilium uninstall` OR `helm uninstall cilium -n kube-system`. Then: remove CNI config from /etc/cni/net.d/, reboot nodes or remove veth/bpffs manually. Install new CNI before pods break</div></div><button class="mcq-toggle-btn" onclick="toggleAnswer('a147')">👁️ Show Answer &amp; Explanation</button><div class="mcq-answer" id="a147"><div class="answer-label">✅ Correct Answer: D</div><p>cilium uninstall cleans up Cilium resources. After uninstall: CNI config still on nodes. Remove /etc/cni/net.d/05-cilium.conf. bpffs cleanup on reboot.</p></div></div>

    <div class="mcq-block" id="q148" data-correct="B"><div class="mcq-number"><span class="domain-pill d5">Installation</span> Q148 of 200</div><div class="mcq-question">Cilium in air-gapped / offline environment?</div><div class="mcq-options"><div class="mcq-option">A) Not supported</div><div class="mcq-option">B) Pre-pull images to private registry. `cilium install --set image.repository=my-registry/cilium/cilium --set operator.image.repository=...`. Use --version for specific tag. Helm chart must be available locally</div><div class="mcq-option">C) Cilium auto-detects offline mode</div><div class="mcq-option">D) Only via manual DaemonSet YAML</div></div><button class="mcq-toggle-btn" onclick="toggleAnswer('a148')">👁️ Show Answer &amp; Explanation</button><div class="mcq-answer" id="a148"><div class="answer-label">✅ Correct Answer: B</div><p>Key images: cilium-agent, operator, hubble-relay, hubble-ui, clustermesh-apiserver, preflight. Mirror all to internal registry. Helm chart: download tgz or use local path.</p></div></div>
    </div>
"""

# =============================================================================
# BATCH 2: Q157–Q168 (Cat 6: Cluster Mesh)
# =============================================================================
MCQS_CAT6 = r"""
    <!-- ═══════════ 6.x: Advanced Cluster Mesh (Q157–Q168) ═══════════ -->
    <div class="section-block" id="cat6-adv"><h3>Advanced Cluster Mesh (Q157–Q168)</h3>

    <div class="mcq-block" id="q157" data-correct="C"><div class="mcq-number"><span class="domain-pill d6">Cluster Mesh</span> Q157 of 200</div><div class="mcq-question">Cluster Mesh service affinity modes?</div><div class="mcq-options"><div class="mcq-option">A) Only random</div><div class="mcq-option">B) Only local preferred</div><div class="mcq-option">C) "local" (prefer local cluster backends, fail to remote), "remote" (prefer remote), "none" (no preference, round-robin across all clusters). Set via annotation: io.cilium/service-affinity</div><div class="mcq-option">D) Always local cluster first</div></div><button class="mcq-toggle-btn" onclick="toggleAnswer('a157')">👁️ Show Answer &amp; Explanation</button><div class="mcq-answer" id="a157"><div class="answer-label">✅ Correct Answer: C</div><p>Annotation: `io.cilium/service-affinity: local`. Use local for low latency, remote for active/passive DR, none for true global load balancing.</p></div></div>

    <div class="mcq-block" id="q158" data-correct="A"><div class="mcq-number"><span class="domain-pill d6">Cluster Mesh</span> Q158 of 200</div><div class="mcq-question">Cluster Mesh etcd — deployment options?</div><div class="mcq-options"><div class="mcq-option">A) External etcd (separate HA cluster, production recommended) OR embedded etcd (cilium clustermesh enable creates internal etcd via StatefulSet). External: managed etcd, K8s etcd, or dedicated cluster</div><div class="mcq-option">B) Only external etcd</div><div class="mcq-option">C) Only embedded etcd</div><div class="mcq-option">D) Uses K8s API server instead of etcd</div></div><button class="mcq-toggle-btn" onclick="toggleAnswer('a158')">👁️ Show Answer &amp; Explanation</button><div class="mcq-answer" id="a158"><div class="answer-label">✅ Correct Answer: A</div><p>External etcd: `--set clustermesh.apiserver.etcd.endpoints=etcd-cluster:2379`. Embedded: simpler for testing. Production: external HA etcd (3+ nodes).</p></div></div>

    <div class="mcq-block" id="q159" data-correct="B"><div class="mcq-number"><span class="domain-pill d6">Cluster Mesh</span> Q159 of 200</div><div class="mcq-question">Cross-cluster NetworkPolicy in Cluster Mesh?</div><div class="mcq-options"><div class="mcq-option">A) Not supported — policies are cluster-local</div><div class="mcq-option">B) CiliumNetworkPolicy can use `fromEntities: [cluster]` for remote clusters. Global identities shared via etcd. Policies referencing labels work across clusters automatically</div><div class="mcq-option">C) Only allow-all between clusters</div><div class="mcq-option">D) Requires separate cross-cluster policy CRD</div></div><button class="mcq-toggle-btn" onclick="toggleAnswer('a159')">👁️ Show Answer &amp; Explanation</button><div class="mcq-answer" id="a159"><div class="answer-label">✅ Correct Answer: B</div><p>Since identities are global (identity@cluster-id), a CNP in cluster-1 can allow/deny traffic from cluster-2 pods. `fromEntities: [cluster]` applies to all clusters.</p></div></div>

    <div class="mcq-block" id="q160" data-correct="D"><div class="mcq-number"><span class="domain-pill d6">Cluster Mesh</span> Q160 of 200</div><div class="mcq-question">Cluster Mesh pod CIDR overlap — what happens?</div><div class="mcq-options"><div class="mcq-option">A) Auto-detects and renumbers</div><div class="mcq-option">B) Works fine — identities handle it</div><div class="mcq-option">C) Only egress works, no ingress</div><div class="mcq-option">D) BREAKS routing — overlapping CIDRs cause wrong routing decisions. Pod IPs must be unique across all clusters. Solution: re-IP or use identity-based routing (future)</div></div><button class="mcq-toggle-btn" onclick="toggleAnswer('a160')">👁️ Show Answer &amp; Explanation</button><div class="mcq-answer" id="a160"><div class="answer-label">✅ Correct Answer: D</div><p>This is why the requirement says "non-overlapping pod CIDRs." If 10.0.0.5 exists in both clusters, routing is ambiguous. Identity doesn't fix IP routing.</p></div></div>

    <div class="mcq-block" id="q161" data-correct="A"><div class="mcq-number"><span class="domain-pill d6">Cluster Mesh</span> Q161 of 200</div><div class="mcq-question">cilium clustermesh status — what does it show?</div><div class="mcq-options"><div class="mcq-option">A) Connected clusters list, their cluster IDs, last heartbeat, shared services count, identities sync status. Shows healthy/down per cluster. Critical for troubleshooting</div><div class="mcq-option">B) Only peer IP addresses</div><div class="mcq-option">C) Same as cilium status</div><div class="mcq-option">D) BGP peer status</div></div><button class="mcq-toggle-btn" onclick="toggleAnswer('a161')">👁️ Show Answer &amp; Explanation</button><div class="mcq-answer" id="a161"><div class="answer-label">✅ Correct Answer: A</div><p>Example output: Cluster-2 (ID:2): ready, 156 identities, 12 shared services, last heartbeat 3s ago. If "down" — check TLS, etcd, network.</p></div></div>

    <div class="mcq-block" id="q162" data-correct="C"><div class="mcq-number"><span class="domain-pill d6">Cluster Mesh</span> Q162 of 200</div><div class="mcq-question">Multi-cluster service — how to create?</div><div class="mcq-options"><div class="mcq-option">A) Automatic for all services</div><div class="mcq-option">B) Special CRD only</div><div class="mcq-option">C) Annotate Service: `io.cilium/global-service: "true"`. The service becomes available in all connected clusters with same ClusterIP. Backends from all clusters aggregated</div><div class="mcq-option">D) kubectl expose with --cluster-mesh flag</div></div><button class="mcq-toggle-btn" onclick="toggleAnswer('a162')">👁️ Show Answer &amp; Explanation</button><div class="mcq-answer" id="a162"><div class="answer-label">✅ Correct Answer: C</div><p>Just add the annotation. If service exists in multiple clusters, backends merged. `cilium service list` shows backends with cluster ID prefix.</p></div></div>

    <div class="mcq-block" id="q163" data-correct="B"><div class="mcq-number"><span class="domain-pill d6">Cluster Mesh</span> Q163 of 200</div><div class="mcq-question">Egress Gateway policy — how to define?</div><div class="mcq-options"><div class="mcq-option">A) Only via Helm values</div><div class="mcq-option">B) CiliumEgressGatewayPolicy CRD: select pods via podSelector, specify destination CIDRs, egress IP. Gateway nodes selected via nodeSelector. Traffic exits from gateway node with fixed IP</div><div class="mcq-option">C) Via CiliumNetworkPolicy egress section</div><div class="mcq-option">D) kubectl annotate pod</div></div><button class="mcq-toggle-btn" onclick="toggleAnswer('a163')">👁️ Show Answer &amp; Explanation</button><div class="mcq-answer" id="a163"><div class="answer-label">✅ Correct Answer: B</div><p>CRD defines: which pods → which destinations → which egress IP → which gateway nodes. Multiple policies can share same gateway. Gateway selection via node labels.</p></div></div>

    <div class="mcq-block" id="q164" data-correct="A"><div class="mcq-number"><span class="domain-pill d6">Cluster Mesh</span> Q164 of 200</div><div class="mcq-question">Cluster Mesh: split-brain scenario?</div><div class="mcq-options"><div class="mcq-option">A) If etcd connectivity lost between clusters, each cluster operates independently with LOCAL backends. When connectivity restores, identities re-sync. No split-brain in data plane — each cluster uses its own etcd</div><div class="mcq-option">B) Both clusters stop working</div><div class="mcq-option">C) Random traffic drops</div><div class="mcq-option">D) Automatic leader election resolves</div></div><button class="mcq-toggle-btn" onclick="toggleAnswer('a164')">👁️ Show Answer &amp; Explanation</button><div class="mcq-answer" id="a164"><div class="answer-label">✅ Correct Answer: A</div><p>Each cluster has its own etcd for local state. Cluster Mesh etcd is for identity+service sync only. During partition: local services continue. Remote backends unreachable until connectivity restores.</p></div></div>

    <div class="mcq-block" id="q165" data-correct="C"><div class="mcq-number"><span class="domain-pill d6">Cluster Mesh</span> Q165 of 200</div><div class="mcq-question">Cross-cluster observability with Hubble?</div><div class="mcq-options"><div class="mcq-option">A) Not possible — Hubble is per-cluster</div><div class="mcq-option">B) Hubble auto-merges all clusters</div><div class="mcq-option">C) Each cluster has its own Hubble Relay + UI. For unified view: aggregate metrics in central Prometheus/Thanos. Hubble CLI can switch contexts to query different clusters</div><div class="mcq-option">D) Only via Cilium CLI</div></div><button class="mcq-toggle-btn" onclick="toggleAnswer('a165')">👁️ Show Answer &amp; Explanation</button><div class="mcq-answer" id="a165"><div class="answer-label">✅ Correct Answer: C</div><p>Hubble is cluster-scoped. For global visibility: Thanos/Cortex for metrics, Grafana with multi-cluster dashboards. Hubble CLI: `hubble observe --context cluster-1`.</p></div></div>

    <div class="mcq-block" id="q166" data-correct="D"><div class="mcq-number"><span class="domain-pill d6">Cluster Mesh</span> Q166 of 200</div><div class="mcq-question">Cluster Mesh vs Service Mesh (Istio/Linkerd)?</div><div class="mcq-options"><div class="mcq-option">A) Same thing — different name</div><div class="mcq-option">B) Cluster Mesh replaces Service Mesh</div><div class="mcq-option">C) Service Mesh replaces Cluster Mesh</div><div class="mcq-option">D) Different layers: Cluster Mesh = L3/L4 multi-cluster networking (IP reachability, routing, identities). Service Mesh = L7 traffic management (retries, timeouts, mTLS, canary). They COMPLEMENT each other — Cilium + Istio is a common pattern</div></div><button class="mcq-toggle-btn" onclick="toggleAnswer('a166')">👁️ Show Answer &amp; Explanation</button><div class="mcq-answer" id="a166"><div class="answer-label">✅ Correct Answer: D</div><p>Cluster Mesh handles HOW pods reach each other across clusters. Service Mesh handles WHAT happens to requests (retries, circuit breaking, tracing). Use together for complete multi-cluster.</p></div></div>

    <div class="mcq-block" id="q167" data-correct="B"><div class="mcq-number"><span class="domain-pill d6">Cluster Mesh</span> Q167 of 200</div><div class="mcq-question">Cluster Mesh bandwidth requirements?</div><div class="mcq-options"><div class="mcq-option">A) No specific requirements</div><div class="mcq-option">B) etcd sync: minimal (KB/s for identity/service updates). Data plane: depends on cross-cluster pod traffic. Recommendation: minimum 10 Mbps between clusters for control plane stability. Latency < 100ms for identity sync</div><div class="mcq-option">C) Only 1 Gbps minimum</div><div class="mcq-option">D) Bandwidth doesn't matter — only latency</div></div><button class="mcq-toggle-btn" onclick="toggleAnswer('a167')">👁️ Show Answer &amp; Explanation</button><div class="mcq-answer" id="a167"><div class="answer-label">✅ Correct Answer: B</div><p>Control plane: lightweight identity sync via etcd watchers. Data plane: whatever your cross-cluster apps need. High latency (>100ms) can slow identity propagation and cause policy delays.</p></div></div>

    <div class="mcq-block" id="q168" data-correct="A"><div class="mcq-number"><span class="domain-pill d6">Cluster Mesh</span> Q168 of 200</div><div class="mcq-question">Cluster Mesh with overlapping services?</div><div class="mcq-options"><div class="mcq-option">A) If same service name exists in multiple clusters, annotating ALL with `global-service: true` MERGES their backends. If only one annotated, that cluster's backends are the global backends. Use service affinity to control routing</div><div class="mcq-option">B) Overlapping services cause errors</div><div class="mcq-option">C) Only one cluster's service wins</div><div class="mcq-option">D) Services must have different names</div></div><button class="mcq-toggle-btn" onclick="toggleAnswer('a168')">👁️ Show Answer &amp; Explanation</button><div class="mcq-answer" id="a168"><div class="answer-label">✅ Correct Answer: A</div><p>Same name + same namespace + global annotation = merged. Pod backends from all clusters. Cilium internally prepends cluster-id to differentiate identical pod IPs.</p></div></div>
    </div>
"""

# =============================================================================
# BATCH 3: Q177–Q188 (Cat 7: eBPF)
# =============================================================================
MCQS_CAT7 = r"""
    <!-- ═══════════ 7.x: Advanced eBPF (Q177–Q188) ═══════════ -->
    <div class="section-block" id="cat7-adv"><h3>Advanced eBPF in Cilium (Q177–Q188)</h3>

    <div class="mcq-block" id="q177" data-correct="B"><div class="mcq-number"><span class="domain-pill d7">eBPF</span> Q177 of 200</div><div class="mcq-question">eBPF verifier — what does it check?</div><div class="mcq-options"><div class="mcq-option">A) Only syntax</div><div class="mcq-option">B) No unbounded loops (must terminate), all pointer accesses checked (null + bounds), no unreachable instructions, max 1M instructions (5.1+), stack size limit (512 bytes), helper function arguments validated. Any violation → program rejected</div><div class="mcq-option">C) Only memory safety</div><div class="mcq-option">D) Runtime behavior monitoring</div></div><button class="mcq-toggle-btn" onclick="toggleAnswer('a177')">👁️ Show Answer &amp; Explanation</button><div class="mcq-answer" id="a177"><div class="answer-label">✅ Correct Answer: B</div><p>The verifier is eBPF's safety guarantee — proves the program cannot crash the kernel. All loops must be provably bounded. Complex programs may need `#pragma unroll`.</p></div></div>

    <div class="mcq-block" id="q178" data-correct="C"><div class="mcq-number"><span class="domain-pill d7">eBPF</span> Q178 of 200</div><div class="mcq-question">BPF CO-RE (Compile Once, Run Everywhere)?</div><div class="mcq-options"><div class="mcq-option">A) Run same binary on any OS</div><div class="mcq-option">B) Cross-architecture compilation</div><div class="mcq-option">C) Single eBPF binary works on different kernel versions via BTF (BPF Type Format). Kernel provides type info at load time. Relocations resolve field offsets. No need to compile per kernel</div><div class="mcq-option">D) Container-optimized eBPF</div></div><button class="mcq-toggle-btn" onclick="toggleAnswer('a178')">👁️ Show Answer &amp; Explanation</button><div class="mcq-answer" id="a178"><div class="answer-label">✅ Correct Answer: C</div><p>Before CO-RE: compile eBPF for each kernel version (like kernel modules). With CO-RE + BTF: one binary, kernel BTF provides struct layouts. Kernel 5.4+ with BTF enabled. Cilium uses CO-RE extensively.</p></div></div>

    <div class="mcq-block" id="q179" data-correct="A"><div class="mcq-number"><span class="domain-pill d7">eBPF</span> Q179 of 200</div><div class="mcq-question">BPF maps in Cilium — types and purposes?</div><div class="mcq-options"><div class="mcq-option">A) HASH: policy lookup, identity map. ARRAY: per-endpoint config. LRU_HASH: connection tracking (conntrack). LPM_TRIE: CIDR routing. PERCPU_HASH: per-CPU counters. SOCKMAP: socket redirection for L7 proxy</div><div class="mcq-option">B) Only HASH maps</div><div class="mcq-option">C) Only ARRAY maps</div><div class="mcq-option">D) Cilium doesn't use BPF maps</div></div><button class="mcq-toggle-btn" onclick="toggleAnswer('a179')">👁️ Show Answer &amp; Explanation</button><div class="mcq-answer" id="a179"><div class="answer-label">✅ Correct Answer: A</div><p>Each map type optimized for specific use: HASH for O(1) policy lookup, LPM for longest-prefix CIDR match, LRU for automatic eviction in conntrack. Inspect: `bpftool map dump pinned /sys/fs/bpf/tc/globals/cilium_ct4_global`.</p></div></div>

    <div class="mcq-block" id="q180" data-correct="B"><div class="mcq-number"><span class="domain-pill d7">eBPF</span> Q180 of 200</div><div class="mcq-question">eBPF hook points used by Cilium?</div><div class="mcq-options"><div class="mcq-option">A) Only XDP</div><div class="mcq-option">B) TC (traffic control) ingress/egress — main policy + LB. XDP (eXpress Data Path) — early DDoS/ACL. Socket — L7 proxy redirection. cgroup — socket-level policy. kprobe/kretprobe — minimal use. Cilium primarily uses TC hooks</div><div class="mcq-option">C) Only cgroup hooks</div><div class="mcq-option">D) Netfilter hooks (same as iptables)</div></div><button class="mcq-toggle-btn" onclick="toggleAnswer('a180')">👁️ Show Answer &amp; Explanation</button><div class="mcq-answer" id="a180"><div class="answer-label">✅ Correct Answer: B</div><p>TC is Cilium's workhorse — attaches to veth host side for ingress+egress. XDP for early drop (optional). Socket for Envoy proxy bypass. cgroup for socket-level enforcement.</p></div></div>

    <div class="mcq-block" id="q181" data-correct="D"><div class="mcq-number"><span class="domain-pill d7">eBPF</span> Q181 of 200</div><div class="mcq-question">Maglev load balancing in eBPF?</div><div class="mcq-options"><div class="mcq-option">A) Traditional round-robin in eBPF</div><div class="mcq-option">B) Random backend selection</div><div class="mcq-option">C) Least-connections algorithm</div><div class="mcq-option">D) Consistent hashing algorithm implemented in eBPF. Backend table with fixed size M (typically 65537). Each backend hashes to ~M/N slots. Backend changes only affect ~1/N of flows. O(1) lookup</div></div><button class="mcq-toggle-btn" onclick="toggleAnswer('a181')">👁️ Show Answer &amp; Explanation</button><div class="mcq-answer" id="a181"><div class="answer-label">✅ Correct Answer: D</div><p>Maglev provides consistent hashing for service backends. When backend is added/removed, only connections mapped to that backend shift — rest unchanged. Critical for connection tracking stability.</p></div></div>

    <div class="mcq-block" id="q182" data-correct="A"><div class="mcq-number"><span class="domain-pill d7">eBPF</span> Q182 of 200</div><div class="mcq-question">eBPF tail calls in Cilium?</div><div class="mcq-options"><div class="mcq-option">A) Chain multiple eBPF programs without returning to kernel. Used for complex policy chains: TC ingress → tail call to policy program → tail call to LB → tail call to forward. Avoids stack overflow, modular design</div><div class="mcq-option">B) Recursive function calls</div><div class="mcq-option">C) System calls from eBPF</div><div class="mcq-option">D) Calling user-space programs</div></div><button class="mcq-toggle-btn" onclick="toggleAnswer('a182')">👁️ Show Answer &amp; Explanation</button><div class="mcq-answer" id="a182"><div class="answer-label">✅ Correct Answer: A</div><p>Tail calls = eBPF's "function call." Max 33 tail calls deep. Cilium uses them for modular policy processing: DNAT → policy → LB → forward. `bpftool prog show` reveals the chain.</p></div></div>

    <div class="mcq-block" id="q183" data-correct="C"><div class="mcq-number"><span class="domain-pill d7">eBPF</span> Q183 of 200</div><div class="mcq-question">eBPF bandwidth management — EDT (Earliest Departure Time)?</div><div class="mcq-options"><div class="mcq-option">A) Token bucket filter in kernel</div><div class="mcq-option">B) HTB qdisc</div><div class="mcq-option">C) eBPF implements EDT rate limiting: each packet gets assigned a departure timestamp. If "now < departure time," packet is queued. Provides precise bandwidth control per-pod without qdisc overhead</div><div class="mcq-option">D) Uses iptables rate limiting</div></div><button class="mcq-toggle-btn" onclick="toggleAnswer('a183')">👁️ Show Answer &amp; Explanation</button><div class="mcq-answer" id="a183"><div class="answer-label">✅ Correct Answer: C</div><p>EDT in eBPF replaces tc-tbf/HTB. More precise, less CPU. Set via CiliumNetworkPolicy: `egress: {bandwidth: "10Mbps"}`. Kernel 5.18+ for BBR + EDT.</p></div></div>

    <div class="mcq-block" id="q184" data-correct="B"><div class="mcq-number"><span class="domain-pill d7">eBPF</span> Q184 of 200</div><div class="mcq-question">bpffs (BPF File System) purpose?</div><div class="mcq-options"><div class="mcq-option">A) Temporary eBPF storage</div><div class="mcq-option">B) Pseudo-filesystem at /sys/fs/bpf/ for PINNING eBPF programs and maps. Pinned objects persist beyond process lifetime. Cilium pins maps at /sys/fs/bpf/tc/globals/cilium_*. Enables sharing between agent and CLI tools</div><div class="mcq-option">C) Logging for eBPF programs</div><div class="mcq-option">D) eBPF source code storage</div></div><button class="mcq-toggle-btn" onclick="toggleAnswer('a184')">👁️ Show Answer &amp; Explanation</button><div class="mcq-answer" id="a184"><div class="answer-label">✅ Correct Answer: B</div><p>Without bpffs: eBPF objects die when the loading process exits. With bpffs: maps survive agent restarts. `ls /sys/fs/bpf/tc/globals/` shows Cilium's pinned objects. `bpftool map show pinned /sys/fs/bpf/...`.</p></div></div>

    <div class="mcq-block" id="q185" data-correct="A"><div class="mcq-number"><span class="domain-pill d7">eBPF</span> Q185 of 200</div><div class="mcq-question">XDP vs TC — when does Cilium use each?</div><div class="mcq-options"><div class="mcq-option">A) TC is primary (all features). XDP is OPTIONAL for early packet drop (DDoS mitigation, ACL). XDP runs BEFORE kernel allocates sk_buff — faster for drop. But XDP can't do L7, LB, conntrack. Cilium uses TC for everything by default</div><div class="mcq-option">B) XDP replaces TC completely</div><div class="mcq-option">C) Both used equally</div><div class="mcq-option">D) XDP for ingress, TC for egress only</div></div><button class="mcq-toggle-btn" onclick="toggleAnswer('a185')">👁️ Show Answer &amp; Explanation</button><div class="mcq-answer" id="a185"><div class="answer-label">✅ Correct Answer: A</div><p>XDP advantage: runs before SKB allocation — 10M+ pps drop capability. Limitation: no stateful processing, no L7. Cilium uses TC 99% of the time. Enable XDP with `--set bpf.acceleration=native`.</p></div></div>

    <div class="mcq-block" id="q186" data-correct="C"><div class="mcq-number"><span class="domain-pill d7">eBPF</span> Q186 of 200</div><div class="mcq-question">eBPF program limit per node?</div><div class="mcq-options"><div class="mcq-option">A) Unlimited</div><div class="mcq-option">B) 10 programs per node</div><div class="mcq-option">C) Cilium loads ~10-20 eBPF programs per endpoint (pod). With 500 pods = 10,000+ programs. Kernel limit: typically 1M total instructions. Practical: depends on kernel memory. Cilium scales to thousands of pods</div><div class="mcq-option">D) 1 program per node</div></div><button class="mcq-toggle-btn" onclick="toggleAnswer('a186')">👁️ Show Answer &amp; Explanation</button><div class="mcq-answer" id="a186"><div class="answer-label">✅ Correct Answer: C</div><p>Each Cilium endpoint (pod) gets TC ingress + egress programs. Kernel handles many programs efficiently. `bpftool prog list | wc -l` to count. `bpftool prog show` for details.</p></div></div>

    <div class="mcq-block" id="q187" data-correct="B"><div class="mcq-number"><span class="domain-pill d7">eBPF</span> Q187 of 200</div><div class="mcq-question">eBPF ring buffer vs perf buffer for observability?</div><div class="mcq-options"><div class="mcq-option">A) Same — different name</div><div class="mcq-option">B) Ring buffer (newer, kernel 5.8+): shared memory, lockless, higher throughput, variable-size records. Perf buffer (older): per-CPU, fixed-size, more CPU overhead. Hubble uses ring buffer for flow events</div><div class="mcq-option">C) Perf buffer is newer</div><div class="mcq-option">D) Hubble doesn't use either</div></div><button class="mcq-toggle-btn" onclick="toggleAnswer('a187')">👁️ Show Answer &amp; Explanation</button><div class="mcq-answer" id="a187"><div class="answer-label">✅ Correct Answer: B</div><p>Ring buffer advantage: no per-CPU ordering issues, better batching, lower overhead. Hubble exports flows from kernel → user space via ring buffer. Kernel 5.8+ recommended.</p></div></div>

    <div class="mcq-block" id="q188" data-correct="A"><div class="mcq-number"><span class="domain-pill d7">eBPF</span> Q188 of 200</div><div class="mcq-question">Cilium eBPF datapath debugging?</div><div class="mcq-options"><div class="mcq-option">A) cilium bpf endpoint list, cilium bpf policy get <ep-id>, cilium bpf ct list, cilium bpf lb list, cilium map list. bpftool for kernel-level: bpftool prog show, bpftool map dump. cilium monitor for live events</div><div class="mcq-option">B) Only cilium monitor</div><div class="mcq-option">C) tcpdump on host interfaces</div><div class="mcq-option">D) No debugging tools — black box</div></div><button class="mcq-toggle-btn" onclick="toggleAnswer('a188')">👁️ Show Answer &amp; Explanation</button><div class="mcq-answer" id="a188"><div class="answer-label">✅ Correct Answer: A</div><p>Debugging layers: cilium CLI (high-level) → bpftool (kernel-level) → cilium monitor (live events). `cilium bpf endpoint list` shows all local endpoints with their BPF program IDs.</p></div></div>
    </div>
"""

# =============================================================================
# BATCH 4: Q195–Q200 (Cat 8: BGP & External Networking)
# =============================================================================
MCQS_CAT8 = r"""
    <!-- ═══════════ 8.x: Advanced BGP & External (Q195–Q200) ═══════════ -->
    <div class="section-block" id="cat8-adv"><h3>Advanced BGP &amp; External Networking (Q195–Q200)</h3>

    <div class="mcq-block" id="q195" data-correct="B"><div class="mcq-number"><span class="domain-pill d8">BGP &amp; External</span> Q195 of 200</div><div class="mcq-question">BGP in Cilium: eBGP vs iBGP support?</div><div class="mcq-options"><div class="mcq-option">A) Only eBGP supported</div><div class="mcq-option">B) Both eBGP (different ASN) and iBGP (same ASN) supported. eBGP: peering with external routers (ToR, upstream). iBGP: peering within same AS (between Cilium nodes or with route reflectors). CiliumBGPPeeringPolicy handles both</div><div class="mcq-option">C) Only iBGP supported</div><div class="mcq-option">D) BGP not supported in Cilium</div></div><button class="mcq-toggle-btn" onclick="toggleAnswer('a195')">👁️ Show Answer &amp; Explanation</button><div class="mcq-answer" id="a195"><div class="answer-label">✅ Correct Answer: B</div><p>Most common: eBGP to ToR switches advertising Service LoadBalancer IPs. iBGP for full mesh between Cilium nodes. Cilium acts as BGP speaker via GoBGP (no FRR needed).</p></div></div>

    <div class="mcq-block" id="q196" data-correct="C"><div class="mcq-number"><span class="domain-pill d8">BGP &amp; External</span> Q196 of 200</div><div class="mcq-question">BGP route advertisement — what gets advertised?</div><div class="mcq-options"><div class="mcq-option">A) All pod IPs</div><div class="mcq-option">B) Only node IPs</div><div class="mcq-option">C) Service LoadBalancer IPs (from LB IPAM or external), pod CIDRs (if cluster mesh or native routing). Controlled by CiliumBGPPeeringPolicy spec.virtualRouters[].serviceSelector and podCIDR advertisement</div><div class="mcq-option">D) Random selection of IPs</div></div><button class="mcq-toggle-btn" onclick="toggleAnswer('a196')">👁️ Show Answer &amp; Explanation</button><div class="mcq-answer" id="a196"><div class="answer-label">✅ Correct Answer: C</div><p>Select services via labels or by name/namespace. Advertise pod CIDRs for native routing without mesh. Each virtual router can advertise different sets of prefixes.</p></div></div>

    <div class="mcq-block" id="q197" data-correct="A"><div class="mcq-number"><span class="domain-pill d8">BGP &amp; External</span> Q197 of 200</div><div class="mcq-question">BGP timers and fast failure detection?</div><div class="mcq-options"><div class="mcq-option">A) BFD (Bidirectional Forwarding Detection) supported for sub-second failure detection. Without BFD: BGP hold timer (default 90s keepalive 30s). Configure: CiliumBGPPeeringPolicy spec.virtualRouters[].neighbors[].bfd</div><div class="mcq-option">B) Only BGP hold timer</div><div class="mcq-option">C) BGP auto-detects failures instantly</div><div class="mcq-option">D) BFD not supported</div></div><button class="mcq-toggle-btn" onclick="toggleAnswer('a197')">👁️ Show Answer &amp; Explanation</button><div class="mcq-answer" id="a197"><div class="answer-label">✅ Correct Answer: A</div><p>Without BFD: failover takes 90s (hold timer). With BFD: ~300ms detection, rapid failover. BFD runs in kernel. Critical for production BGP deployments.</p></div></div>

    <div class="mcq-block" id="q198" data-correct="D"><div class="mcq-number"><span class="domain-pill d8">BGP &amp; External</span> Q198 of 200</div><div class="mcq-question">L2 Announcements — leader election mechanism?</div><div class="mcq-options"><div class="mcq-option">A) Raft consensus</div><div class="mcq-option">B) Random node selection</div><div class="mcq-option">C) Round-robin between nodes</div><div class="mcq-option">D) Kubernetes Lease-based leader election. One node per service acquires lease → becomes ARP responder. If node dies, lease expires (default 15s TTL), another node acquires it. Renew interval: 5s</div></div><button class="mcq-toggle-btn" onclick="toggleAnswer('a198')">👁️ Show Answer &amp; Explanation</button><div class="mcq-answer" id="a198"><div class="answer-label">✅ Correct Answer: D</div><p>Lease name: `cilium-l2announce-<service-hash>`. Each service gets its own lease. Node with lease = ARP responder. Failover: lease TTL + detection time (~15-20s total).</p></div></div>

    <div class="mcq-block" id="q199" data-correct="B"><div class="mcq-number"><span class="domain-pill d8">BGP &amp; External</span> Q199 of 200</div><div class="mcq-question">Ingress Controller vs Gateway API in Cilium?</div><div class="mcq-options"><div class="mcq-option">A) Only Ingress supported</div><div class="mcq-option">B) Both supported. Ingress: `--set ingressController.enabled=true`, standard K8s Ingress with CiliumEnvoyConfig. Gateway API: `--set gatewayAPI.enabled=true`, newer standard (HTTPRoute, Gateway). Both use Envoy as data plane</div><div class="mcq-option">C) Only Gateway API supported</div><div class="mcq-option">D) Neither — Cilium doesn't do L7 ingress</div></div><button class="mcq-toggle-btn" onclick="toggleAnswer('a199')">👁️ Show Answer &amp; Explanation</button><div class="mcq-answer" id="a199"><div class="answer-label">✅ Correct Answer: B</div><p>Gateway API is the future (more expressive than Ingress). Both use Envoy proxy embedded in Cilium agent or as DaemonSet. CiliumEnvoyConfig CRD gives full Envoy configuration control.</p></div></div>

    <div class="mcq-block" id="q200" data-correct="A"><div class="mcq-number"><span class="domain-pill d8">BGP &amp; External</span> Q200 of 200</div><div class="mcq-question">Cilium BGP — what GoBGP features are exposed?</div><div class="mcq-options"><div class="mcq-option">A) IPv4/IPv6 unicast, BFD, graceful restart, communities (standard + large), AS path prepend, local preference, MED, multi-hop peering, password authentication (MD5). Not exposed: flowspec, MPLS, EVPN, route reflection (use external RR)</div><div class="mcq-option">B) Only basic IPv4 peering</div><div class="mcq-option">C) Full GoBGP feature set</div><div class="mcq-option">D) No BGP features — uses FRR instead</div></div><button class="mcq-toggle-btn" onclick="toggleAnswer('a200')">👁️ Show Answer &amp; Explanation</button><div class="mcq-answer" id="a200"><div class="answer-label">✅ Correct Answer: A</div><p>Cilium embeds GoBGP. Exposes ~70% of GoBGP features through CiliumBGPPeeringPolicy CRD. Advanced features like flowspec/EVPN not needed for Cilium's use case (Service advertisement).</p></div></div>
    </div>
"""

# =============================================================================
# Insert all batches
# =============================================================================

with open(HTML_PATH, "r", encoding="utf-8") as f:
    content = f.read()

# --- Batch 1: Q137-Q148 in Cat5 ---
# Find the closing of Q136 block and the end of cat5 section, before cat6 starts
marker1 = '</div></div>\n    </div></section>\n\n    <section class="chapter-section" id="cat6">'
replacement1 = '</div></div>\n' + MCQS_CAT5.strip() + '\n    </div></section>\n\n    <section class="chapter-section" id="cat6">'
if marker1 in content:
    content = content.replace(marker1, replacement1, 1)
    print("✅ Batch 1: Q137-Q148 inserted into Cat5")
else:
    print("❌ Batch 1 marker not found!")
    # Try alternative marker
    marker1b = '</div></section>\n\n    <section class="chapter-section" id="cat6">'
    if marker1b in content:
        replacement1b = MCQS_CAT5.strip() + '\n    </div></section>\n\n    <section class="chapter-section" id="cat6">'
        content = content.replace(marker1b, replacement1b, 1)
        print("✅ Batch 1 (alt): Q137-Q148 inserted into Cat5")
    else:
        print("❌ Batch 1 alt marker also not found!")

# --- Batch 2: Q157-Q168 in Cat6 ---
marker2 = '</div></div>\n    </div></section>\n\n    <section class="chapter-section" id="cat7">'
replacement2 = '</div></div>\n' + MCQS_CAT6.strip() + '\n    </div></section>\n\n    <section class="chapter-section" id="cat7">'
if marker2 in content:
    content = content.replace(marker2, replacement2, 1)
    print("✅ Batch 2: Q157-Q168 inserted into Cat6")
else:
    print("❌ Batch 2 marker not found!")

# --- Batch 3: Q177-Q188 in Cat7 ---
marker3 = '</div></div>\n    </div></section>\n\n    <section class="chapter-section" id="cat8">'
replacement3 = '</div></div>\n' + MCQS_CAT7.strip() + '\n    </div></section>\n\n    <section class="chapter-section" id="cat8">'
if marker3 in content:
    content = content.replace(marker3, replacement3, 1)
    print("✅ Batch 3: Q177-Q188 inserted into Cat7")
else:
    print("❌ Batch 3 marker not found!")

# --- Batch 4: Q195-Q200 in Cat8 ---
marker4 = '</div></div>\n\n    </div></section>\n\n    <!-- ═══════════════ PART 2 ═══════════════ -->'
replacement4 = '</div></div>\n' + MCQS_CAT8.strip() + '\n\n    </div></section>\n\n    <!-- ═══════════════ PART 2 ═══════════════ -->'
if marker4 in content:
    content = content.replace(marker4, replacement4, 1)
    print("✅ Batch 4: Q195-Q200 inserted into Cat8")
else:
    print("❌ Batch 4 marker not found!")
    # Try alt
    marker4b = '\n    </div></section>\n\n    <!-- ═══════════════ PART 2 ═══════════════ -->'
    if marker4b in content:
        replacement4b = '\n' + MCQS_CAT8.strip() + '\n\n    </div></section>\n\n    <!-- ═══════════════ PART 2 ═══════════════ -->'
        content = content.replace(marker4b, replacement4b, 1)
        print("✅ Batch 4 (alt): Q195-Q200 inserted into Cat8")
    else:
        print("❌ Batch 4 alt marker also not found!")

with open(HTML_PATH, "w", encoding="utf-8") as f:
    f.write(content)

print("\n🎉 Done! All MCQ batches processed.")
