$f = "c:\Users\owner\Desktop\DEV-DOCs\KUBERNETES - 5\networking.html"
Write-Host "Loading..."
$html = [System.IO.File]::ReadAllText($f, [System.Text.Encoding]::UTF8)
$origKB = [math]::Round($html.Length/1KB,0)
Write-Host "Size: $origKB KB"

# Exam prep content per chapter
$examBoxes = @{
    '1' = @'
                <div class="info-box tip"><h5>🎯 Chapter 1 Exam Prep — OSI &amp; TCP/IP Models</h5><p><strong>Exam Weight: HIGH (15-20% of questions)</strong></p><div class="card-grid"><div class="info-card"><h5>📋 Must Memorize</h5><ul><li>7 OSI layers bottom-up: Physical→Data Link→Network→Transport→Session→Presentation→Application</li><li>PDU per layer: Bits→Frames→Packets→Segments→Data</li><li>TCP/IP 4 layers: Link→Internet→Transport→Application</li><li>Mnemonic: <strong>P</strong>lease <strong>D</strong>o <strong>N</strong>ot <strong>T</strong>hrow <strong>S</strong>ausage <strong>P</strong>izza <strong>A</strong>way</li></ul></div><div class="info-card"><h5>⚠️ Common Traps</h5><ul><li>"Ping works = network is fine" — ICMP only tests L1-L3!</li><li>Router=L3 (by IP), Switch=L2 (by MAC), Hub=L1 (repeat bits)</li><li>TLS is L6 (Presentation), NOT L7</li><li>Bottom-up debugging order is ALWAYS tested</li></ul></div><div class="info-card"><h5>🔧 Quick Commands</h5><ul><li><code>ping</code> — L3 reachability</li><li><code>traceroute</code> — Path discovery</li><li><code>ss -tlnp</code> — L4 port check</li><li><code>curl -v</code> — L7 app test</li><li><code>tcpdump -i any -nn</code> — All layers</li></ul></div></div></div>
'@
    '2' = @'
                <div class="info-box tip"><h5>🎯 Chapter 2 Exam Prep — Physical Layer &amp; Ethernet</h5><p><strong>Exam Weight: MEDIUM (10% of questions)</strong></p><div class="card-grid"><div class="info-card"><h5>📋 Must Memorize</h5><ul><li>Ethernet frame: Preamble(8B)+DstMAC(6B)+SrcMAC(6B)+EthType(2B)+Payload(46-1500B)+FCS(4B)</li><li>EthType values: 0x0800=IPv4, 0x0806=ARP, 0x86DD=IPv6, 0x8100=VLAN</li><li>CSMA/CD: Carrier Sense → Multiple Access → Collision Detection</li><li>Switch 3 Fs: Flood(unknown), Forward(known), Filter(same port)</li></ul></div><div class="info-card"><h5>⚠️ Common Traps</h5><ul><li>"Link UP" does NOT mean link is healthy — check error counters!</li><li>Duplex mismatch = collisions on one side, late collisions on the other</li><li>VXLAN overhead (50B) reduces effective MTU → PMTU black holes</li><li>Auto-negotiation is MANDATORY at 1 Gbps and above</li></ul></div><div class="info-card"><h5>🔧 Quick Commands</h5><ul><li><code>ethtool eth0</code> — Speed, duplex, link state</li><li><code>ip -s link show eth0</code> — Error counters</li><li><code>ip link show eth0</code> — MTU, state, MAC</li><li><code>bridge fdb show br br0</code> — MAC table</li><li><code>arping -I eth0 IP</code> — L2 reachability</li></ul></div></div></div>
'@
    '3' = @'
                <div class="info-box tip"><h5>🎯 Chapter 3 Exam Prep — ARP, MAC &amp; Switching</h5><p><strong>Exam Weight: MEDIUM (8-10% of questions)</strong></p><div class="card-grid"><div class="info-card"><h5>📋 Must Memorize</h5><ul><li>ARP: Broadcast request "Who has IP X?" → Unicast reply with MAC</li><li>ARP table cached (ip neigh), entries time out (default ~60s stale)</li><li>Gratuitous ARP: unsolicited ARP for duplicate IP detection &amp; MAC update</li><li>Proxy ARP: router answers ARP on behalf of remote hosts</li><li>MAC types: Unicast(bit0=0), Multicast(bit0=1), Broadcast(ff:ff:ff:ff:ff:ff)</li></ul></div><div class="info-card"><h5>⚠️ Common Traps</h5><ul><li>ARP spoofing/poisoning = MITM attack — use DAI or static ARP</li><li>Stale ARP entries cause "network works, then breaks" issues</li><li>ARP only works within the same L2 broadcast domain</li><li>ip neigh != arp command (ip is the modern replacement)</li></ul></div><div class="info-card"><h5>🔧 Quick Commands</h5><ul><li><code>ip neigh show</code> — View ARP table</li><li><code>arping -I eth0 192.168.1.5</code> — Test ARP</li><li><code>ip neigh add/del</code> — Static ARP</li><li><code>tcpdump -i eth0 arp</code> — Capture ARP traffic</li></ul></div></div></div>
'@
    '4' = @'
                <div class="info-box tip"><h5>🎯 Chapter 4 Exam Prep — VLANs &amp; 802.1Q</h5><p><strong>Exam Weight: MEDIUM (8-10% of questions)</strong></p><div class="card-grid"><div class="info-card"><h5>📋 Must Memorize</h5><ul><li>802.1Q tag: 4 bytes (TPID=0x8100 + PCP/DEI/VID 12-bit=4094 VLANs)</li><li>Access port: single untagged VLAN; Trunk port: multiple tagged VLANs</li><li>Native VLAN: untagged frames on trunk (default VLAN 1)</li><li>VLAN hopping: double-tagging attack mitigation</li></ul></div><div class="info-card"><h5>⚠️ Common Traps</h5><ul><li>VLAN 1 is the default native VLAN — change it for security!</li><li>Untagged frames on trunk use the native VLAN</li><li>802.1Q tag adds 4 bytes → frame size up to 1522 bytes</li><li>Inter-VLAN routing requires L3 device (router or L3 switch)</li></ul></div><div class="info-card"><h5>🔧 Quick Commands</h5><ul><li><code>ip link add link eth0 name eth0.10 type vlan id 10</code></li><li><code>cat /proc/net/vlan/config</code> — VLAN config</li><li><code>bridge vlan show</code> — Bridge VLAN table</li></ul></div></div></div>
'@
    '5' = @'
                <div class="info-box tip"><h5>🎯 Chapter 5 Exam Prep — IP Addressing &amp; Subnetting</h5><p><strong>Exam Weight: VERY HIGH (20% of questions)</strong></p><div class="card-grid"><div class="info-card"><h5>📋 Must Memorize</h5><ul><li>CIDR /8=255.0.0.0(16M), /16=255.255.0.0(65K), /24=255.255.255.0(256)</li><li>Network=IP AND mask; Broadcast=Network OR ~mask; Hosts=2^(32-prefix)-2</li><li>RFC 1918: 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16</li><li>Special: 127.0.0.0/8(loopback), 169.254.0.0/16(link-local), 0.0.0.0(wildcard)</li></ul></div><div class="info-card"><h5>⚠️ Common Traps</h5><ul><li>First IP in subnet = network address (unusable); Last = broadcast</li><li>Subnet zero rule is OBSOLETE (use subnet-zero)</li><li>VLSM: different subnet masks in same network</li><li>/31 subnets exist for point-to-point links (no broadcast)</li></ul></div><div class="info-card"><h5>🔧 Quick Commands</h5><ul><li><code>ipcalc 192.168.1.0/24</code> — Subnet calculator</li><li><code>ip addr show</code> — Interface IPs</li><li><code>sipcalc eth0</code> — Detailed IP info</li></ul></div></div></div>
'@
    '6' = @'
                <div class="info-box tip"><h5>🎯 Chapter 6 Exam Prep — Routing Fundamentals</h5><p><strong>Exam Weight: HIGH (12-15% of questions)</strong></p><div class="card-grid"><div class="info-card"><h5>📋 Must Memorize</h5><ul><li>Longest prefix match: more specific route wins over less specific</li><li>Default route: 0.0.0.0/0 (matches everything, lowest priority)</li><li>Administrative distance: Connected=0, Static=1, OSPF=110, BGP(eBGP=20,iBGP=200)</li><li>Routing table selection: Longest match → AD → Metric</li></ul></div><div class="info-card"><h5>⚠️ Common Traps</h5><ul><li>ip route get DST shows which route will be used (test before deploy!)</li><li>Asymmetric routing: forward path != return path → firewall drops</li><li>Missing return route is the #1 cause of "can ping but can't connect"</li><li>Routing loops: TTL prevents infinite loops (max 255, default 64)</li></ul></div><div class="info-card"><h5>🔧 Quick Commands</h5><ul><li><code>ip route show</code> — View routing table</li><li><code>ip route get 8.8.8.8</code> — Route lookup test</li><li><code>ip route add 10.0.0.0/8 via 192.168.1.254</code></li><li><code>traceroute -n HOST</code> — Per-hop path</li></ul></div></div></div>
'@
    '7' = @'
                <div class="info-box tip"><h5>🎯 Chapter 7 Exam Prep — Dynamic Routing (OSPF/BGP)</h5><p><strong>Exam Weight: MEDIUM (8-10% of questions)</strong></p><div class="card-grid"><div class="info-card"><h5>📋 Must Memorize</h5><ul><li>OSPF: Link-state, Area 0(backbone), DR/BDR on broadcast networks, multicast 224.0.0.5/6</li><li>BGP: Path-vector, TCP/179, AS-path for loop prevention</li><li>eBGP(AS-to-AS, AD=20) vs iBGP(within AS, AD=200)</li><li>OSPF states: Down→Init→2-Way→ExStart→Exchange→Loading→Full</li></ul></div><div class="info-card"><h5>⚠️ Common Traps</h5><ul><li>iBGP full mesh requirement (or route reflectors/confederations)</li><li>OSPF areas must connect to Area 0 (backbone)</li><li>BGP does NOT automatically load balance (multipath must be configured)</li><li>IGP(OSPF/EIGRP) + BGP: IGP for reachability, BGP for policy</li></ul></div><div class="info-card"><h5>🔧 Quick Commands</h5><ul><li><code>ip route show protocol bgp</code> — BGP routes</li><li><code>birdc show protocols</code> — BIRD routing daemon</li><li><code>vtysh -c "show ip ospf neighbor"</code> — OSPF neighbors</li></ul></div></div></div>
'@
    '8' = @'
                <div class="info-box tip"><h5>🎯 Chapter 8 Exam Prep — TCP Deep Dive</h5><p><strong>Exam Weight: VERY HIGH (15-20% of questions)</strong></p><div class="card-grid"><div class="info-card"><h5>📋 Must Memorize</h5><ul><li>3-way handshake: SYN→, ←SYN-ACK, ACK→ (ESTABLISHED)</li><li>4-way close: FIN→, ←ACK, ←FIN, ACK→ (TIME_WAIT=2MSL)</li><li>TCP states: LISTEN, SYN_SENT/RECVD, ESTABLISHED, FIN_WAIT1/2, TIME_WAIT, CLOSE_WAIT</li><li>Flow control: sliding window (rwnd); Congestion control: cwnd (CUBIC/BBR)</li></ul></div><div class="info-card"><h5>⚠️ Common Traps</h5><ul><li>TIME_WAIT: 2MSL(60s) — normal, not a problem (tcp_tw_reuse)</li><li>CLOSE_WAIT: app didn't call close() → socket leak (check ss -tpn)</li><li>Connection refused(RST) vs Timeout(SYN dropped by firewall)</li><li>TCP retransmits = packet loss signal, not necessarily congestion</li></ul></div><div class="info-card"><h5>🔧 Quick Commands</h5><ul><li><code>ss -tpn state established</code> — Active connections</li><li><code>ss -tin | grep retrans</code> — Retransmit counters</li><li><code>tcpdump -i any 'tcp[tcpflags] & (tcp-syn|tcp-fin) != 0'</code> — Flag filter</li></ul></div></div></div>
'@
    '9' = @'
                <div class="info-box tip"><h5>🎯 Chapter 9 Exam Prep — UDP &amp; Transport Layer</h5><p><strong>Exam Weight: MEDIUM (8% of questions)</strong></p><div class="card-grid"><div class="info-card"><h5>📋 Must Memorize</h5><ul><li>UDP: Connectionless, 8B header, no retransmission, no ordering</li><li>Common UDP: DNS:53, DHCP:67/68, NTP:123, SNMP:161, QUIC:443, VoIP/RTP</li><li>TCP vs UDP: reliable/ordered vs fast/low-overhead</li><li>QUIC: UDP-based, built-in TLS 1.3, 0-RTT handshake, HTTP/3 uses it</li></ul></div><div class="info-card"><h5>⚠️ Common Traps</h5><ul><li>"UDP is unreliable" — but QUIC adds reliability at the application layer</li><li>UDP checksum is optional in IPv4 (MANDATORY in IPv6)</li><li>traceroute traditionally uses UDP (high ports) — newer versions use TCP</li><li>DNS uses BOTH UDP(queries) and TCP(zone transfers, large responses)</li></ul></div><div class="info-card"><h5>🔧 Quick Commands</h5><ul><li><code>ss -ulpn</code> — UDP listeners</li><li><code>nc -uz HOST PORT</code> — UDP connectivity test</li><li><code>tcpdump -i any udp port 53</code> — Capture UDP DNS</li></ul></div></div></div>
'@
    '10' = @'
                <div class="info-box tip"><h5>🎯 Chapter 10 Exam Prep — ICMP &amp; Diagnostics</h5><p><strong>Exam Weight: HIGH (10-12% of questions)</strong></p><div class="card-grid"><div class="info-card"><h5>📋 Must Memorize</h5><ul><li>ICMP types: 0(Echo Reply), 8(Echo Request), 3(Dest Unreachable), 11(TTL Exceeded)</li><li>Dest Unreachable codes: 0(Net), 1(Host), 3(Port), 4(Frag needed/DF set)</li><li>traceroute: TTL=1,2,3... + ICMP Type 11 from each hop</li><li>PMTU discovery: uses ICMP "frag needed" (type 3 code 4)</li></ul></div><div class="info-card"><h5>⚠️ Common Traps</h5><ul><li>ping tests L1-L3 ONLY — does NOT test TCP ports (use nc -zv)!</li><li>Firewalls often allow ICMP but block TCP → "ping works, app doesn't"</li><li>PMTU black hole: ICMP frag-needed blocked → TCP stalls (MSS clamping fix)</li><li>ICMP rate limiting: some hosts limit ICMP replies → packet loss false positive</li></ul></div><div class="info-card"><h5>🔧 Quick Commands</h5><ul><li><code>ping -c 10 -i 0.2 HOST</code> — Fast ping</li><li><code>mtr -r HOST</code> — Combined ping+traceroute</li><li><code>traceroute -n -T HOST</code> — TCP traceroute</li></ul></div></div></div>
'@
    '11' = @'
                <div class="info-box tip"><h5>🎯 Chapter 11 Exam Prep — DNS Deep Dive</h5><p><strong>Exam Weight: HIGH (12-15% of questions)</strong></p><div class="card-grid"><div class="info-card"><h5>📋 Must Memorize</h5><ul><li>Resolution: Browser→OS(/etc/hosts)→Resolver→Root→TLD→Authoritative NS</li><li>Record types: A(IPv4), AAAA(IPv6), CNAME(alias), MX(mail), TXT, NS, SOA, PTR, SRV</li><li>Recursive vs iterative queries; Forward vs reverse DNS (PTR records)</li><li>Port 53: UDP for queries, TCP for zone transfers &amp; large responses</li></ul></div><div class="info-card"><h5>⚠️ Common Traps</h5><ul><li>CNAME at apex (root domain) is INVALID per RFC</li><li>TTL expiration causes "sometimes works" DNS issues</li><li>Negative caching: NXDOMAIN cached per SOA TTL</li><li>DNS over HTTPS(DoH)/TLS(DoT) changes troubleshooting visibility</li></ul></div><div class="info-card"><h5>🔧 Quick Commands</h5><ul><li><code>dig +trace DOMAIN</code> — Full resolution path</li><li><code>dig DOMAIN ANY</code> — All records</li><li><code>nslookup DOMAIN</code> — Quick lookup</li><li><code>resolvectl status</code> — systemd-resolved</li></ul></div></div></div>
'@
    '12' = @'
                <div class="info-box tip"><h5>🎯 Chapter 12 Exam Prep — HTTP/HTTPS &amp; Web Protocols</h5><p><strong>Exam Weight: HIGH (10-12% of questions)</strong></p><div class="card-grid"><div class="info-card"><h5>📋 Must Memorize</h5><ul><li>HTTP methods: GET(read), POST(create), PUT(replace), PATCH(update), DELETE(remove)</li><li>Status codes: 2xx(OK), 3xx(redirect), 4xx(client error), 5xx(server error)</li><li>HTTP/1.1: keep-alive, pipelining; HTTP/2: binary, multiplex, HPACK; HTTP/3: QUIC/UDP</li><li>Headers: Host, Content-Type, Authorization, Cookie, Cache-Control, CORS</li></ul></div><div class="info-card"><h5>⚠️ Common Traps</h5><ul><li>401 vs 403: Unauthorized(no creds) vs Forbidden(has creds, no access)</li><li>HTTP/2 requires HTTPS in browsers (TLS mandatory)</li><li>CORS errors = browser-side protection (server gets request but blocks response)</li><li>gRPC uses HTTP/2 — requires special L7 load balancer support</li></ul></div><div class="info-card"><h5>🔧 Quick Commands</h5><ul><li><code>curl -sv https://HOST</code> — Verbose HTTP</li><li><code>curl -I https://HOST</code> — Headers only</li><li><code>curl -o /dev/null -w "%{http_code}" https://HOST</code> — Status code</li></ul></div></div></div>
'@
    '13' = @'
                <div class="info-box tip"><h5>🎯 Chapter 13 Exam Prep — TLS/SSL &amp; Certificates</h5><p><strong>Exam Weight: HIGH (10-12% of questions)</strong></p><div class="card-grid"><div class="info-card"><h5>📋 Must Memorize</h5><ul><li>TLS 1.3: 1-RTT handshake; TLS 1.2: 2-RTT; TLS operates at OSI L6 (Presentation)</li><li>Certificate chain: Root CA → Intermediate CA → Leaf/Server cert</li><li>PKI: public/private key pair; CSR→CA signs→Certificate</li><li>Cipher suites: key exchange(ECDHE)+auth(RSA/ECDSA)+encryption(AES-GCM)+hash(SHA256)</li></ul></div><div class="info-card"><h5>⚠️ Common Traps</h5><ul><li>Certificate expiration is the #1 cause of TLS outages</li><li>Wildcard certs (*.domain.com) match ONE subdomain level only</li><li>Self-signed certs require explicit trust store configuration</li><li>SNI (Server Name Indication) required for multiple certs on one IP</li></ul></div><div class="info-card"><h5>🔧 Quick Commands</h5><ul><li><code>openssl s_client -connect HOST:443 -servername HOST</code></li><li><code>openssl x509 -in cert.pem -noout -dates</code> — Expiry check</li><li><code>openssl verify -CAfile ca.pem cert.pem</code> — Chain verify</li></ul></div></div></div>
'@
    '14' = @'
                <div class="info-box tip"><h5>🎯 Chapter 14 Exam Prep — DHCP &amp; Address Assignment</h5><p><strong>Exam Weight: MEDIUM (5-8% of questions)</strong></p><div class="card-grid"><div class="info-card"><h5>📋 Must Memorize</h5><ul><li>DORA: Discover→Offer→Request→Acknowledge</li><li>Ports: client=68/UDP, server=67/UDP</li><li>Lease process: T1(50%)=renew, T2(87.5%)=rebind, expiration=release</li><li>DHCP options: 1=subnet mask, 3=router, 6=DNS servers, 15=domain name</li></ul></div><div class="info-card"><h5>⚠️ Common Traps</h5><ul><li>DHCP relay needed across L3 boundaries (broadcast stays in subnet)</li><li>Rogue DHCP servers cause network chaos (DHCP snooping mitigation)</li><li>APIPA/169.254.x.x = DHCP failed, auto-configured link-local address</li><li>DHCP vs static: DHCP is preferred in enterprise (IPAM integration)</li></ul></div><div class="info-card"><h5>🔧 Quick Commands</h5><ul><li><code>dhclient -v eth0</code> — Renew lease</li><li><code>cat /var/lib/dhcp/dhclient.leases</code> — Lease DB</li><li><code>tcpdump -i eth0 port 67 or port 68 -v</code></li></ul></div></div></div>
'@
    '15' = @'
                <div class="info-box tip"><h5>🎯 Chapter 15 Exam Prep — NAT &amp; Port Forwarding</h5><p><strong>Exam Weight: MEDIUM (8-10% of questions)</strong></p><div class="card-grid"><div class="info-card"><h5>📋 Must Memorize</h5><ul><li>SNAT/Masquerade: changes SRC IP (POSTROUTING chain)</li><li>DNAT: changes DST IP (PREROUTING chain)</li><li>PAT/NAPT: NAT + port translation (most common home/office NAT)</li><li>Full-cone, Restricted-cone, Port-restricted, Symmetric NAT types</li></ul></div><div class="info-card"><h5>⚠️ Common Traps</h5><ul><li>NAT breaks end-to-end connectivity principle of the Internet</li><li>Conntrack table overflow = new connections dropped (monitor size!)</li><li>NAT hairpinning: internal client accessing public IP of internal server</li><li>Carrier-Grade NAT (CGNAT): 100.64.0.0/10 — double NAT scenarios</li></ul></div><div class="info-card"><h5>🔧 Quick Commands</h5><ul><li><code>conntrack -L</code> — Connection tracking</li><li><code>iptables -t nat -L -nv</code> — NAT rules</li><li><code>cat /proc/net/nf_conntrack</code> — Conntrack table</li></ul></div></div></div>
'@
    '16' = @'
                <div class="info-box tip"><h5>🎯 Chapter 16 Exam Prep — Firewalls &amp; iptables/nftables</h5><p><strong>Exam Weight: HIGH (10-12% of questions)</strong></p><div class="card-grid"><div class="info-card"><h5>📋 Must Memorize</h5><ul><li>iptables chains: INPUT, OUTPUT, FORWARD, PREROUTING(DNAT), POSTROUTING(SNAT)</li><li>Tables: filter(default), nat, mangle, raw, security</li><li>Targets: ACCEPT, DROP(silent), REJECT(ICMP), LOG, RETURN, DNAT, SNAT, MASQUERADE</li><li>nftables: modern replacement, unified syntax, better performance</li></ul></div><div class="info-card"><h5>⚠️ Common Traps</h5><ul><li>DROP vs REJECT: DROP causes timeout, REJECT gives instant feedback</li><li>Rule order matters! First match wins (put ESTABLISHED,RELATED early)</li><li>iptables rules are NOT persistent by default (iptables-save needed)</li><li>FORWARD chain is for routed traffic (not local processes)</li></ul></div><div class="info-card"><h5>🔧 Quick Commands</h5><ul><li><code>iptables -L -nv --line-numbers</code> — List rules</li><li><code>iptables-save > /etc/iptables/rules.v4</code> — Persist</li><li><code>nft list ruleset</code> — nftables view</li></ul></div></div></div>
'@
    '17' = @'
                <div class="info-box tip"><h5>🎯 Chapter 17 Exam Prep — Load Balancing &amp; Reverse Proxies</h5><p><strong>Exam Weight: MEDIUM (8-10% of questions)</strong></p><div class="card-grid"><div class="info-card"><h5>📋 Must Memorize</h5><ul><li>Algorithms: round-robin, least_conn, ip_hash, random, least_time</li><li>Reverse proxy: terminates client TLS, forwards to backend (often plain HTTP)</li><li>L4 LB: IP+port based; L7 LB: HTTP path/host/cookie based</li><li>Health checks: active(probe) vs passive(observe failures)</li></ul></div><div class="info-card"><h5>⚠️ Common Traps</h5><ul><li>Sticky sessions break horizontal scaling (use shared session store instead)</li><li>Proxy protocol needed to preserve client IP through L4 LB</li><li>X-Forwarded-For header can be spoofed (trust only from known proxy)</li><li>Backend connection pooling: max_conns prevents overload</li></ul></div><div class="info-card"><h5>🔧 Quick Commands</h5><ul><li><code>nginx -t && nginx -s reload</code> — Test+reload config</li><li><code>curl -H "Host: app.com" http://PROXY</code> — Test routing</li></ul></div></div></div>
'@
    '18' = @'
                <div class="info-box tip"><h5>🎯 Chapter 18 Exam Prep — Kubernetes Pod Networking</h5><p><strong>Exam Weight: VERY HIGH (15-20% of questions)</strong></p><div class="card-grid"><div class="info-card"><h5>📋 Must Memorize</h5><ul><li>Pod: shared network namespace (same IP, localhost, ports across containers)</li><li>CNI: ADD/DEL/CHECK/VERSION operations; config in /etc/cni/net.d/</li><li>veth pairs: one end in pod NS, other attached to cni0 bridge on node</li><li>IP-per-pod model: every pod gets a unique, routable IP</li></ul></div><div class="info-card"><h5>⚠️ Common Traps</h5><ul><li>Pod IPs are ephemeral — always use Services for stable addressing</li><li>Container port conflicts within a pod (shared NS means shared ports!)</li><li>hostNetwork: true bypasses CNI entirely (security risk!)</li><li>CNI plugin must handle IPAM, routing, and potentially NetworkPolicy</li></ul></div><div class="info-card"><h5>🔧 Quick Commands</h5><ul><li><code>kubectl exec POD -- ip addr</code> — Pod interfaces</li><li><code>kubectl exec POD -- ip route</code> — Pod routing</li><li><code>kubectl get pods -o wide</code> — Pod IPs &amp; nodes</li></ul></div></div></div>
'@
    '19' = @'
                <div class="info-box tip"><h5>🎯 Chapter 19 Exam Prep — Kubernetes Services</h5><p><strong>Exam Weight: VERY HIGH (15-20% of questions)</strong></p><div class="card-grid"><div class="info-card"><h5>📋 Must Memorize</h5><ul><li>ClusterIP: internal-only virtual IP; NodePort: 30000-32767 on all nodes; LoadBalancer: cloud LB</li><li>kube-proxy modes: iptables(random DNAT), IPVS(better perf, scheduling algorithms)</li><li>Endpoints: list of ready pod IP:ports for a Service; EndpointSlices: scalable alternative</li><li>headless Service (clusterIP: None): DNS returns pod IPs directly</li></ul></div><div class="info-card"><h5>⚠️ Common Traps</h5><ul><li>ClusterIP is NOT reachable from outside the cluster (need LB/NodePort/Ingress)</li><li>NodePort opens on ALL nodes (security consideration!)</li><li>externalTrafficPolicy: Local preserves client IP but may imbalance</li><li>Service without selectors: manually manage Endpoints (external services)</li></ul></div><div class="info-card"><h5>🔧 Quick Commands</h5><ul><li><code>kubectl get svc,ep -A</code> — All services &amp; endpoints</li><li><code>kubectl expose deploy NAME --port=80 --target-port=8080</code></li><li><code>kubectl describe svc NAME</code> — Service details</li></ul></div></div></div>
'@
    '20' = @'
                <div class="info-box tip"><h5>🎯 Chapter 20 Exam Prep — Kubernetes NetworkPolicy</h5><p><strong>Exam Weight: HIGH (10-15% of questions)</strong></p><div class="card-grid"><div class="info-card"><h5>📋 Must Memorize</h5><ul><li>podSelector + policyTypes(Ingress/Egress) + ingress/egress rules</li><li>Default: ALLOW ALL traffic (no policy = no restrictions)</li><li>First policy applied = implicit deny-all for specified traffic type</li><li>Namespaces: namespaceSelector for cross-namespace policies</li></ul></div><div class="info-card"><h5>⚠️ Common Traps</h5><ul><li>NetworkPolicy requires a CNI that supports it (Calico, Cilium, Weave)</li><li>Flannel alone does NOT support NetworkPolicy (needs Calico extension)</li><li>podSelector: {} = all pods in namespace (empty is DIFFERENT from absent)</li><li>Egress rules easily forgotten → DNS resolution blocked (allow UDP 53!)</li></ul></div><div class="info-card"><h5>🔧 Quick Commands</h5><ul><li><code>kubectl get netpol -A</code> — All policies</li><li><code>kubectl describe netpol NAME -n NS</code> — Policy details</li></ul></div></div></div>
'@
    '21' = @'
                <div class="info-box tip"><h5>🎯 Chapter 21 Exam Prep — Kubernetes Ingress &amp; Gateway API</h5><p><strong>Exam Weight: HIGH (10-12% of questions)</strong></p><div class="card-grid"><div class="info-card"><h5>📋 Must Memorize</h5><ul><li>Ingress: L7 HTTP(S) routing (host+path), TLS termination, requires Ingress Controller</li><li>Gateway API: GatewayClass→Gateway→HTTPRoute; role separation (infra vs dev)</li><li>Annotations on Ingress for controller-specific config (rewrite, CORS, rate-limit)</li><li>IngressClassName: specifies which controller handles the Ingress</li></ul></div><div class="info-card"><h5>⚠️ Common Traps</h5><ul><li>Ingress resource does nothing without an Ingress Controller (nginx, traefik, etc.)</li><li>Default backend handles unmatched requests (404 by default)</li><li>TLS secret must be in the same namespace as the Ingress</li><li>Gateway API is the future — Ingress is not deprecated but being superseded</li></ul></div><div class="info-card"><h5>🔧 Quick Commands</h5><ul><li><code>kubectl get ingress -A</code> — All Ingresses</li><li><code>kubectl describe ingress NAME -n NS</code></li><li><code>curl -H "Host: app.com" http://INGRESS_IP</code></li></ul></div></div></div>
'@
    '22' = @'
                <div class="info-box tip"><h5>🎯 Chapter 22 Exam Prep — Container Networking &amp; Docker</h5><p><strong>Exam Weight: MEDIUM (8-10% of questions)</strong></p><div class="card-grid"><div class="info-card"><h5>📋 Must Memorize</h5><ul><li>Docker network drivers: bridge(default), host, overlay(Swarm), macvlan, none</li><li>Bridge: docker0(172.17.0.0/16), veth pairs, NAT for outbound</li><li>Overlay: VXLAN-based, container-to-container across hosts</li><li>docker-compose creates a default bridge network per project</li></ul></div><div class="info-card"><h5>⚠️ Common Traps</h5><ul><li>--network host: containers share host network (port conflicts!)</li><li>Container DNS: 127.0.0.11 (Docker embedded DNS)</li><li>docker-compose service name = DNS name (use as hostname)</li><li>MTU issues with overlay networks (VXLAN overhead)</li></ul></div><div class="info-card"><h5>🔧 Quick Commands</h5><ul><li><code>docker network ls</code> — List networks</li><li><code>docker network inspect NAME</code> — Network details</li><li><code>docker run --network=NAME IMAGE</code></li></ul></div></div></div>
'@
    '23' = @'
                <div class="info-box tip"><h5>🎯 Chapter 23 Exam Prep — CNI Plugins Deep Dive</h5><p><strong>Exam Weight: MEDIUM (8-10% of questions)</strong></p><div class="card-grid"><div class="info-card"><h5>📋 Must Memorize</h5><ul><li>Flannel: simple L3 overlay (VXLAN or host-gw), no NetworkPolicy alone</li><li>Calico: BGP or IPIP, native NetworkPolicy, high performance</li><li>Cilium: eBPF-based, L7 policies, Hubble observability, service mesh</li><li>Weave: mesh overlay, encryption, NetworkPolicy, simple setup</li></ul></div><div class="info-card"><h5>⚠️ Common Traps</h5><ul><li>CNI choice impacts: NetworkPolicy support, performance, observability, encryption</li><li>Calico with IPIP adds 20B overhead (reduce MTU)</li><li>Cilium requires kernel 4.9+ for eBPF features</li><li>Migration between CNIs requires node recreation in most cases</li></ul></div><div class="info-card"><h5>🔧 Quick Commands</h5><ul><li><code>kubectl get pods -n kube-system | grep -E "calico|flannel|cilium|weave"</code></li><li><code>ls /etc/cni/net.d/</code> — CNI config files</li></ul></div></div></div>
'@
    '24' = @'
                <div class="info-box tip"><h5>🎯 Chapter 24 Exam Prep — Network Troubleshooting Methodology</h5><p><strong>Exam Weight: VERY HIGH (15-20% of questions)</strong></p><div class="card-grid"><div class="info-card"><h5>📋 Must Memorize</h5><ul><li>Bottom-up approach: L1→L2→L3→L4→L7 (ALWAYS start at lowest layer)</li><li>5-step checklist: ip link → ip neigh → ping → ss/nc → curl/dig</li><li>Divide &amp; conquer: test from both ends towards the middle</li><li>Compare working vs non-working: same host? same network? same app?</li></ul></div><div class="info-card"><h5>⚠️ Common Traps</h5><ul><li>"It was working yesterday" → check for recent changes first</li><li>DNS is the hidden dependency (cached vs fresh, different resolvers)</li><li>Firewall changes are the #1 cause of "sudden" network issues</li><li>Packet captures don't lie — if you're stuck, tcpdump!</li></ul></div><div class="info-card"><h5>🔧 Quick Commands</h5><ul><li><code>tcpdump -i any -nn host IP -w debug.pcap</code></li><li><code>mtr -r HOST</code> — Per-hop loss/latency</li><li><code>ss -tlnp</code> — What's listening?</li></ul></div></div></div>
'@
    '25' = @'
                <div class="info-box tip"><h5>🎯 Chapter 25 Exam Prep — Network Performance &amp; Monitoring</h5><p><strong>Exam Weight: MEDIUM (5-8% of questions)</strong></p><div class="card-grid"><div class="info-card"><h5>📋 Must Memorize</h5><ul><li>Bandwidth(Mbps) vs Throughput(actual) vs Goodput(usable data)</li><li>Latency(RTT ms), Jitter(latency variation), Packet Loss(%)</li><li>iperf3 for bandwidth testing; mtr for per-hop latency/loss</li><li>SNMP for device monitoring; NetFlow/sFlow for flow data</li></ul></div><div class="info-card"><h5>⚠️ Common Traps</h5><ul><li>Bandwidth != speed — throughput is always less due to overhead</li><li>Bufferbloat: excess buffering hides packet loss but adds latency</li><li>TCP throughput limit: ~ (MSS/RTT) / sqrt(loss) → Mathis equation</li><li>Monitoring the wrong metric (interface bytes vs application errors)</li></ul></div><div class="info-card"><h5>🔧 Quick Commands</h5><ul><li><code>iperf3 -s</code>(server) / <code>iperf3 -c HOST -t 30</code>(client)</li><li><code>ethtool -S eth0</code> — NIC statistics</li></ul></div></div></div>
'@
    '26' = @'
                <div class="info-box tip"><h5>🎯 Chapter 26 Exam Prep — Network Security Fundamentals</h5><p><strong>Exam Weight: HIGH (10-12% of questions)</strong></p><div class="card-grid"><div class="info-card"><h5>📋 Must Memorize</h5><ul><li>Defense in depth: L2(port security, DAI), L3(ACLs), L4(firewall), L7(WAF)</li><li>Common attacks: DDoS, MITM(ARP spoofing), DNS poisoning, SYN flood, amplification</li><li>Segmentation: VLANs, VRFs, micro-segmentation (K8s NetworkPolicy)</li><li>Zero Trust: never trust, always verify; micro-segmentation at workload level</li></ul></div><div class="info-card"><h5>⚠️ Common Traps</h5><ul><li>Encryption at rest != encryption in transit (both needed)</li><li>Default credentials are still the #1 network security failure</li><li>Security groups / NSGs are stateful (return traffic auto-allowed)</li><li>Network ACLs are stateless (must explicitly allow return traffic)</li></ul></div><div class="info-card"><h5>🔧 Quick Commands</h5><ul><li><code>nmap -sS -p- HOST</code> — Port scan</li><li><code>tcpdump -i any 'tcp[tcpflags] & tcp-syn != 0'</code> — SYN flood detect</li></ul></div></div></div>
'@
    '27' = @'
                <div class="info-box tip"><h5>🎯 Chapter 27 Exam Prep — VPN &amp; Tunneling</h5><p><strong>Exam Weight: MEDIUM (5-8% of questions)</strong></p><div class="card-grid"><div class="info-card"><h5>📋 Must Memorize</h5><ul><li>IPsec: ESP(encryption+auth) vs AH(auth only); Tunnel vs Transport mode</li><li>WireGuard: modern, simple, kernel-based, UDP, Curve25519+ChaCha20</li><li>GRE: simple encapsulation, no encryption (often paired with IPsec)</li><li>VXLAN: L2 overlay over L3, 24-bit VNI, UDP port 4789</li></ul></div><div class="info-card"><h5>⚠️ Common Traps</h5><ul><li>IPsec behind NAT: NAT-T encapsulates ESP in UDP 4500</li><li>MTU issues with any tunnel (overhead reduces effective MTU)</li><li>WireGuard is stateless (no connection tracking) — easier to manage</li><li>VPN split tunneling: only route specific traffic through VPN</li></ul></div><div class="info-card"><h5>🔧 Quick Commands</h5><ul><li><code>wg show</code> — WireGuard status</li><li><code>ip xfrm state</code> — IPsec SAs</li><li><code>ip link add vxlan0 type vxlan id 100 ...</code></li></ul></div></div></div>
'@
    '28' = @'
                <div class="info-box tip"><h5>🎯 Chapter 28 Exam Prep — Cloud Networking (AWS/Azure/GCP)</h5><p><strong>Exam Weight: MEDIUM (8-10% of questions)</strong></p><div class="card-grid"><div class="info-card"><h5>📋 Must Memorize</h5><ul><li>AWS VPC: CIDR block, subnets per AZ, route tables, IGW, NAT Gateway, SG/NACL</li><li>Azure VNet: address space, subnets, NSG, UDR, VNet peering, ExpressRoute</li><li>GCP VPC: global by default, subnets per region, firewall rules, Cloud NAT</li><li>Common: private link/endpoint for service-to-service without Internet</li></ul></div><div class="info-card"><h5>⚠️ Common Traps</h5><ul><li>Security Groups = stateful (return auto); NACLs = stateless (explicit return)</li><li>NAT Gateway is per-AZ in AWS (single-AZ = SPOF)</li><li>VPC peering is NOT transitive (A-B + B-C != A-C)</li><li>Cloud provider IP ranges change — don't hardcode!</li></ul></div><div class="info-card"><h5>🔧 Quick Commands</h5><ul><li><code>aws ec2 describe-vpcs</code></li><li><code>az network vnet list</code></li><li><code>gcloud compute networks list</code></li></ul></div></div></div>
'@
    '29' = @'
                <div class="info-box tip"><h5>🎯 Chapter 29 Exam Prep — Network Automation &amp; IaC</h5><p><strong>Exam Weight: MEDIUM (5-8% of questions)</strong></p><div class="card-grid"><div class="info-card"><h5>📋 Must Memorize</h5><ul><li>Terraform: aws_vpc, aws_subnet, aws_security_group, aws_route_table resources</li><li>Ansible: network modules (ios_config, nxos_vlan, eos_vlan)</li><li>NetDevOps: CI/CD for network config, Git as source of truth</li><li>Python: netmiko, napalm, nornir for network automation</li></ul></div><div class="info-card"><h5>⚠️ Common Traps</h5><ul><li>terraform destroy removes EVERYTHING — use lifecycle prevent_destroy</li><li>Network changes are riskier than app changes (can't rollback easily)</li><li>Always plan before apply: terraform plan -out=tfplan</li><li>State file contains secrets — use remote backend with encryption</li></ul></div><div class="info-card"><h5>🔧 Quick Commands</h5><ul><li><code>terraform plan</code>, <code>terraform apply</code></li><li><code>ansible-playbook -i inventory network.yml --check</code></li></ul></div></div></div>
'@
    '30' = @'
                <div class="info-box tip"><h5>🎯 Chapter 30 Exam Prep — IPv6 Essentials</h5><p><strong>Exam Weight: MEDIUM (8-10% of questions)</strong></p><div class="card-grid"><div class="info-card"><h5>📋 Must Memorize</h5><ul><li>128-bit address (8 groups of 4 hex digits); compression: omit leading zeros, :: for zeros</li><li>Types: ::1/128(loopback), fe80::/10(link-local), fc00::/7(ULA), 2000::/3(global unicast)</li><li>No broadcast! Uses multicast (ff02::1=all nodes, ff02::2=all routers)</li><li>SLAAC: router sends prefix, host generates IID; DHCPv6 for stateful addressing</li></ul></div><div class="info-card"><h5>⚠️ Common Traps</h5><ul><li>IPv6 is enabled by default on most OS — security implications!</li><li>Dual-stack: run IPv4 AND IPv6 simultaneously (not migration, coexistence)</li><li>NAT not needed in IPv6 (address abundance) — firewall still needed!</li><li>/64 is the standard subnet size (not /24 like IPv4)</li></ul></div><div class="info-card"><h5>🔧 Quick Commands</h5><ul><li><code>ip -6 addr show</code> — IPv6 addresses</li><li><code>ping6 fe80::1%eth0</code> — Link-local ping</li><li><code>traceroute6 HOST</code> — IPv6 traceroute</li></ul></div></div></div>
'@
    '31' = @'
                <div class="info-box tip"><h5>🎯 Chapter 31 Exam Prep — Network Design Patterns</h5><p><strong>Exam Weight: MEDIUM (5-8% of questions)</strong></p><div class="card-grid"><div class="info-card"><h5>📋 Must Memorize</h5><ul><li>3-tier: Access(distribution)→Aggregation→Core (traditional DC)</li><li>Spine-Leaf: every leaf connects to every spine (modern DC, equal-cost paths)</li><li>Hub-and-Spoke: central hub connects all sites (VPN, transit gateway)</li><li>Mesh: full(expensive) vs partial(selective peering)</li></ul></div><div class="info-card"><h5>⚠️ Common Traps</h5><ul><li>Oversubscription ratio: access-to-aggregation (3:1 to 20:1 typical)</li><li>East-West traffic dominates in modern DCs (spine-leaf optimized for this)</li><li>Single points of failure in hub-and-spoke (hub redundancy critical)</li><li>ECMP: equal-cost multi-path for load distribution across parallel links</li></ul></div><div class="info-card"><h5>🔧 Quick Commands</h5><ul><li>Diagrams are your best tool — draw before you deploy!</li><li>Document: subnet plan, VLAN plan, routing design, firewall rules</li></ul></div></div></div>
'@
    '32' = @'
                <div class="info-box tip"><h5>🎯 Chapter 32 Exam Prep — SDN &amp; Network Virtualization</h5><p><strong>Exam Weight: LOW-MEDIUM (5% of questions)</strong></p><div class="card-grid"><div class="info-card"><h5>📋 Must Memorize</h5><ul><li>SDN: decouples control plane from data plane (centralized controller)</li><li>OpenFlow: protocol between controller and switches (flow table rules)</li><li>NFV: virtualize network functions (vRouter, vFW, vLB) on commodity hardware</li><li>Overlay networks: VXLAN, NVGRE, Geneve — L2 over L3 underlay</li></ul></div><div class="info-card"><h5>⚠️ Common Traps</h5><ul><li>Underlay vs Overlay: underlay handles physical transport, overlay handles tenant isolation</li><li>SDN != NFV — SDN is architecture, NFV is function virtualization</li><li>Controller HA is critical (single controller = SPOF)</li><li>OpenFlow adoption limited — most SDN uses proprietary protocols</li></ul></div></div></div>
'@
    '33' = @'
                <div class="info-box tip"><h5>🎯 Chapter 33 Exam Prep — WiFi &amp; Wireless Networking</h5><p><strong>Exam Weight: LOW (5% of questions)</strong></p><div class="card-grid"><div class="info-card"><h5>📋 Must Memorize</h5><ul><li>802.11 standards: a(5GHz), b(2.4GHz), g(2.4GHz), n(WiFi4), ac(WiFi5,5GHz), ax(WiFi6/6E)</li><li>2.4GHz: 11 channels(US), only 1/6/11 non-overlapping; 5GHz: 25+ channels</li><li>Security: WPA2(AES)+802.1X(Enterprise), WPA3(SAE/Simultaneous Auth of Equals)</li><li>CSMA/CA: collision avoidance (not detection like Ethernet)</li></ul></div><div class="info-card"><h5>⚠️ Common Traps</h5><ul><li>WiFi is half-duplex (shared medium) — throughput << link rate</li><li>Channel overlap on 2.4GHz causes co-channel interference</li><li>Hidden node problem: two clients can't hear each other but both reach AP</li><li>Signal strength (dBm) vs SNR: strong signal with high noise = bad</li></ul></div></div></div>
'@
    '34' = @'
                <div class="info-box tip"><h5>🎯 Chapter 34 Exam Prep — Multicast &amp; Streaming</h5><p><strong>Exam Weight: LOW (3-5% of questions)</strong></p><div class="card-grid"><div class="info-card"><h5>📋 Must Memorize</h5><ul><li>Multicast: one-to-many efficient delivery; L3: 224.0.0.0/4(IPv4), ff00::/8(IPv6)</li><li>IGMP: hosts signal interest to router; PIM: router-to-router multicast routing</li><li>PIM modes: Dense Mode(flood+prune), Sparse Mode(join-based, RP needed)</li><li>SSM(Source-Specific Multicast): IGMPv3, no RP needed</li></ul></div><div class="info-card"><h5>⚠️ Common Traps</h5><ul><li>Multicast is NOT broadcast — only subscribed hosts receive</li><li>RP(Rendezvous Point) is single point of failure in PIM-SM</li><li>Multicast across WAN requires ISP support (MBGP/MSDP)</li><li>Most cloud providers do NOT support multicast (use app-layer alternatives)</li></ul></div></div></div>
'@
    '35' = @'
                <div class="info-box tip"><h5>🎯 Chapter 35 Exam Prep — QoS &amp; Traffic Shaping</h5><p><strong>Exam Weight: LOW-MEDIUM (5% of questions)</strong></p><div class="card-grid"><div class="info-card"><h5>📋 Must Memorize</h5><ul><li>QoS mechanisms: Classification→Marking→Queuing→Scheduling→Shaping/Policing</li><li>DSCP: 6-bit field in IP header (replaces old ToS); Classes: EF(46), AFxy, BE(0)</li><li>Queuing: FIFO, PQ(strict), WFQ/CBWFQ(weighted), LLQ(priority+bandwidth)</li><li>Policing(drop excess) vs Shaping(buffer excess, smoother)</li></ul></div><div class="info-card"><h5>⚠️ Common Traps</h5><ul><li>QoS markings are only effective if ALL hops honor them (end-to-end)</li><li>ISP typically strips/resets DSCP markings (trust boundary)</li><li>Shaping adds latency (buffering) — trade-off between smoothness and delay</li><li>Voice/Video need low latency+jitter (LLQ), not just bandwidth</li></ul></div><div class="info-card"><h5>🔧 Quick Commands</h5><ul><li><code>tc qdisc show dev eth0</code> — Linux traffic control</li><li><code>tc -s class show dev eth0</code> — Class stats</li></ul></div></div></div>
'@
    '36' = @'
                <div class="info-box tip"><h5>🎯 Chapter 36 Exam Prep — Network Storage (NFS/iSCSI)</h5><p><strong>Exam Weight: LOW (3-5% of questions)</strong></p><div class="card-grid"><div class="info-card"><h5>📋 Must Memorize</h5><ul><li>NFS: file-level, NFSv3(UDP/TCP 2049, stateless), NFSv4(TCP 2049, stateful, Kerberos)</li><li>iSCSI: block-level, SCSI over TCP(port 3260), initiator↔target</li><li>Jumbo frames (MTU 9000) strongly recommended for storage networks</li><li>Storage network should be isolated (separate VLAN or physical network)</li></ul></div><div class="info-card"><h5>⚠️ Common Traps</h5><ul><li>NFS root squash: root on client mapped to nobody (security feature)</li><li>iSCSI multipathing for redundancy and bandwidth</li><li>MTU mismatch on storage network = severe performance degradation</li><li>NFS hangs = client blocks indefinitely (use soft mount or timeouts)</li></ul></div><div class="info-card"><h5>🔧 Quick Commands</h5><ul><li><code>showmount -e SERVER</code> — NFS exports</li><li><code>iscsiadm -m discovery -t st -p PORTAL</code></li></ul></div></div></div>
'@
    '37' = @'
                <div class="info-box tip"><h5>🎯 Chapter 37 Exam Prep — Network Time Protocol (NTP)</h5><p><strong>Exam Weight: LOW (3-5% of questions)</strong></p><div class="card-grid"><div class="info-card"><h5>📋 Must Memorize</h5><ul><li>NTP: hierarchical (stratum 0→1→2...→15), UDP port 123</li><li>Stratum 0: atomic clock/GPS; Stratum 1: directly connected; Stratum 2+: derived</li><li>NTP uses UTC exclusively (timezone is OS-level conversion)</li><li>PTP (IEEE 1588): sub-microsecond precision for financial/HFT/telecom</li></ul></div><div class="info-card"><h5>⚠️ Common Traps</h5><ul><li>Clock skew > 5 minutes = TLS certificate validation failures</li><li>Distributed systems need synchronized clocks (logs, transactions, auth)</li><li>Virtual machines drift more (no hardware clock) — use host time sync</li><li>NTP pool vs dedicated servers: pool for general, dedicated for critical</li></ul></div><div class="info-card"><h5>🔧 Quick Commands</h5><ul><li><code>timedatectl status</code> — Time/date status</li><li><code>ntpq -p</code> — NTP peer status</li><li><code>chronyc sources -v</code> — Chrony sources</li></ul></div></div></div>
'@
    '38' = @'
                <div class="info-box tip"><h5>🎯 Chapter 38 Exam Prep — Putting It All Together</h5><p><strong>Exam Weight: HIGH (final integration)</strong></p><div class="card-grid"><div class="info-card"><h5>📋 Must Memorize</h5><ul><li>End-to-end troubleshooting: DNS→TCP/TLS→HTTP→Backend→Database</li><li>K8s networking full path: Ingress→Service→Endpoint→Pod→Container</li><li>Observability stack: metrics(Prometheus), logs(Loki), traces(Tempo/Jaeger)</li><li>Network automation: GitOps for network config, CI/CD pipelines</li></ul></div><div class="info-card"><h5>⚠️ Common Traps</h5><ul><li>"It''s the network" — but 70% of the time it''s the application config</li><li>Always check DNS first (hidden dependency in EVERY connection)</li><li>Certificates expire silently — monitor proactively</li><li>Document your network — the diagram you save is the one you need</li></ul></div><div class="info-card"><h5>🔧 Quick Commands</h5><ul><li><code>curl -sv https://APP | jq .</code> — App connectivity test</li><li><code>kubectl run test --rm -it --image=busybox -- nslookup SVC</code></li></ul></div></div></div>
'@
}

# Find each chapter practice question section and insert exam box before it
$pattern = '(<div class="net-exam-questions">)\s*<h4>[^<]*Chapter (\d+) .* Practice Questions</h4>'
$matches = [regex]::Matches($html, $pattern)
Write-Host "Found $($matches.Count) chapter practice sections"

# Process in reverse to preserve positions
$injections = @()
foreach ($m in $matches) {
    $chNum = $m.Groups[2].Value
    $position = $m.Groups[1].Index  # position of <div class="net-exam-questions">
    if ($examBoxes.ContainsKey($chNum)) {
        $injections += @{ pos = $position; html = $examBoxes[$chNum] }
        Write-Host "  Ch $chNum : scheduled"
    } else {
        Write-Host "  Ch $chNum : NO exam box defined! Skipping."
    }
}

Write-Host "Will inject $($injections.Count) exam-prep boxes"

# Apply in reverse order
$sorted = $injections | Sort-Object -Property pos -Descending
$cnt = 0
foreach ($inj in $sorted) {
    $html = $html.Substring(0, $inj.pos) + $inj.html + $html.Substring($inj.pos)
    $cnt++
}

Write-Host "Writing..."
[System.IO.File]::WriteAllText($f, $html, [System.Text.UTF8Encoding]::new($false))
$newKB = [math]::Round((Get-Item $f).Length/1KB,0)
Write-Host "Size: $origKB -> $newKB KB (+$($newKB-$origKB)KB)"
Write-Host "Added $cnt exam-prep boxes"
