
$f = "c:\Users\owner\Desktop\DEV-DOCs\KUBERNETES - 5\networking.html"
$html = Get-Content $f -Raw
$sz0 = [math]::Round($html.Length/1KB,0)
Write-Host "Size before: $sz0 KB"

# Find all exam-question-item blocks that have eq-answer but no eq-explanation
# Pattern: these end with </div></details></div> (answer close, details close, item close)

# We need to replace each orphan </div></details></div> with an explanation version
# But we need different explanations per chapter topic

# Topic-based explanations for orphan questions
$topics = @{
    'ch5' = @('Subnetting: usable hosts = 2^(32-prefix) - 2. Always subtract network and broadcast addresses. /24=254, /26=62, /30=2 for point-to-point links.','Longest prefix match: more specific route always wins. /32 > /24 > /0. This is how the entire internet routes work. BGP advertises increasingly specific prefixes.','DF flag prevents fragmentation. When set and packet exceeds MTU, router drops and sends ICMP Frag Needed. If ICMP blocked, creates PMTU black hole.','ECMP uses 5-tuple hash for flow-consistent load balancing across equal-cost paths. Scales bandwidth while maintaining per-flow ordering.','RFC 1918: 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16. Not routable on public internet. K8s pod CIDR typically uses 10.0.0.0/8 range.','K8s pod routing across nodes uses L3 forwarding via CNI-added routes. No NAT -- pod IPs are real, routable addresses within the cluster. This is the key difference from Docker networking.','PMTU black holes: SSH works but HTTPS POST hangs. Fix with lower MTU or TCP MSS clamping. Cloud security groups default-deny ICMP, making this common.','VPC CIDR (10.0.0.0/16) must not overlap with pod CIDR (10.244.0.0/16) or peered VPCs. Per-AZ /18 subnets provide headroom for scaling. /24 per node keeps routing simple.')
    'ch6' = @('IPv6 uses 128-bit addresses (340 undecillion). Header simplified to fixed 40 bytes with no checksum. Eliminates NAT entirely.','Link-local (fe80::/10) auto-assigned on every IPv6 interface. Never routed. Used for NDP, router discovery, and as next-hop.','Dual-stack runs IPv4 and IPv6 simultaneously. Pods get both address families. CoreDNS returns both A and AAAA records. Supported since K8s v1.23.','IPv6 shortening: leading zeros omitted, longest zero run replaced with :: (once only). Original always has 8 groups -- count to verify.','NDP replaces ARP using ICMPv6 (Type 135 NS, Type 136 NA). Also handles router discovery, prefix discovery, DAD. Uses multicast instead of broadcast.','NAT was never a security feature -- it was an address shortage stopgap. IPv6 restores end-to-end connectivity. Must configure host firewalls properly.','No broadcast in IPv6 -- multicast replaces all broadcast functions. Link-local=fe80::, ULA=fd00::, Global=2000::/3, Loopback=::1, Multicast=ff00::/8.','Router Advertisement (RA) is the most important NDP feature. Routers send prefix, MTU, DHCPv6 flag, default gateway. Critical for IPv6 autoconfiguration.','The -6 flag is universal IPv6 mode: ip -6, ss -6, ping6, curl -6. In K8s: kubectl exec pod -- ip -6 addr show.','IPv4 and IPv6 coexist via dual-stack for decades. Mobile carriers already mostly IPv6-only with 464XLAT for IPv4. Cloud providers charge for public IPv4 addresses.')
    'ch7' = @('Traceroute exploits TTL expiration (RFC 1812). Each router MUST send ICMP Time Exceeded. *** means router suppresses ICMP or firewall blocks.','PMTU black holes: SSH works but HTTPS POST hangs. Fix: lower MTU or TCP MSS clamping. Cloud security groups default-deny ICMP inbound.','Connection refused (RST) = host alive, port closed. Connection timeout = host unreachable or packets dropped. This distinction immediately narrows debugging.','Know ICMP types cold: Type 8/0=ping, Type 3 Code 1=host unreachable, Code 3=port unreachable, Code 4=frag needed. Type 11=time exceeded (traceroute).','ping -M do -s N tests MTU. Start at 1472 (1500 MTU), reduce until it works. Largest working size + 28 = path MTU. Essential for VPN/tunnel debugging.','ping=quick check, traceroute=find which hop, mtr=continuous per-hop analysis. mtr is most powerful for intermittent issues. Loss at hop N not persisting = false positive.','Three reasons for ***: router suppresses ICMP, firewall blocks ICMP, probe lost. *** does not mean broken if subsequent hops respond.','Network Unreachable (Code 0) = no route. Host Unreachable (Code 1) = route exists but no ARP reply. Port Unreachable (Code 3) = from host, no listener.','ICMP allowed but TCP blocked = ping works, nc fails. NetworkPolicy can allow one protocol while denying another. Always test with actual application protocol.','mtr combines continuous ping+traceroute. Shows per-hop latency and loss over time. Use mtr --tcp for reliable results in cloud environments where ICMP is blocked.')
    'ch8' = @('TCP 3-way handshake: SYN (seq=x), SYN-ACK (seq=y, ack=x+1), ACK (ack=y+1). Both sides learn initial sequence numbers. 1 RTT before data flows.','Sequence numbers track bytes sent; ACK numbers track next expected byte. Both sides maintain independent seq/ack. TCP is byte-stream oriented, not packet oriented.','TCP flags: SYN=start, ACK=acknowledge, FIN=close, RST=reset/refuse, PSH=push to app, URG=urgent. RST when no listener = Connection Refused.','4-tuple uniquely identifies each connection: (src_ip, src_port, dst_ip, dst_port). Kernel uses this for conntrack. Same client can have many connections via different source ports.','TCP options: MSS (max segment, MTU-40), Window Scale (multiply by 2^n), SACK (better loss recovery), Timestamps (RTT, PAWS). Negotiated during 3-way handshake.','CLOSE_WAIT is the #1 app bug. Remote sent FIN, kernel ACKed, but app has NOT called close(). Stays forever. Check: ss -t state close-wait.','TIME_WAIT is normal cleanup: active closer waits 2*MSL (60s) to ensure remote got final ACK. High TIME_WAIT = many short-lived outbound connections.','4-way close: FIN_WAIT_1 -> FIN_WAIT_2 -> TIME_WAIT -> CLOSED. Passive side: CLOSE_WAIT -> LAST_ACK -> CLOSED. Steps 2+3 can combine for 3-way close.','Connection refused (RST) = port not open. Connection timeout (no response) = packets dropped. This tells you whether to check the app (refused) or network (timeout).','TCP is reliable: ACKs, retransmission, in-order delivery, no duplication, flow control, congestion control. Cost: latency (handshake), HOL blocking, overhead.')
    'ch9' = @('Congestion control: Reno, CUBIC (Linux default), BBR (Google). CWND starts small, grows with ACKs. Slow start doubles each RTT; congestion avoidance grows linearly.','Flow control via receive window prevents overwhelming receiver. Zero window = buffer full, app not reading. Window scaling enables >64KB for high-BDP paths.','Nagels algorithm + Delayed ACK can cause 200ms+ delays for small request-response. Disable Nagle with TCP_NODELAY for low-latency apps.','SACK lets receiver report exactly which segments arrived. Without SACK, one loss causes retransmission of everything after. Critical for high-BDP paths.','BBR uses bandwidth+RTT measurements, not loss, as congestion signal. Better for WiFi/mobile with some loss. Unlike CUBIC, BBR does not interpret loss as congestion.','BDP = bandwidth x RTT. Optimal window size. 10Gbps 50ms RTT needs 62.5MB window. Without window scaling (max 64KB), high-speed links severely underutilized.','TCP buffer auto-tuning dynamically adjusts socket buffers. Check /proc/sys/net/ipv4/tcp_rmem if throughput unexpectedly low on high-speed links.','SYN cookies protect against SYN floods: encode connection info in SYN-ACK sequence. No state allocated until handshake completes. Auto-enabled under attack.','TCP Fast Open (TFO): data in SYN saves one RTT. Requires client+server support. Enable: sysctl net.ipv4.tcp_fastopen=3. Big improvement for short-lived connections.','TCP pacing smooths bursts, preventing microbursts that overflow switch buffers. Without pacing, full window sent at line rate causing jitter and loss.')
    'ch10' = @('UDP is connectionless: no handshake, no state, no ACKs. Fast but unreliable -- app handles loss/ordering. Minimal 8-byte header.','UDP ideal for DNS, real-time media, gaming, QUIC/HTTP3. Not for file transfers or DB queries needing guaranteed delivery.','UDP header: src port(2), dst port(2), length(2), checksum(2). Compare TCP 20-60 bytes. No sequence numbers, no ACKs, no window.','UDP checksum optional in IPv4, mandatory in IPv6. NICs offload calculation. Wrong checksums in tcpdump? Disable offloading: ethtool -K eth0 tx off rx off.','QUIC builds TCP-like reliability on UDP: 0-RTT, stream multiplexing without HOLB, connection migration. HTTP/3 runs on QUIC. Becoming default web protocol.','UDP fragmentation is fragile and often blocked. Unlike TCP which segments to fit MTU, UDP relies on IP fragmentation. Keep datagrams under 1472 bytes.','DNS uses UDP 53 primarily, TCP fallback for >512 byte responses. UDP preferred for low-overhead query-response pairs.','UDP conntrack uses timeout-based tracking (no state machine). Default 30s vs TCP ESTABLISHED 5 days. Entry removed after timeout.','UDP has no built-in congestion control. QUIC and other UDP-based protocols must implement their own congestion control for fairness.','K8s CoreDNS uses UDP 53 for DNS. NetworkPolicy must allow both UDP and TCP 53. UDP-only DNS silently fails if response exceeds 512 bytes and TCP is blocked.')
    'ch18' = @('K8s Services provide stable virtual IPs for ephemeral pods. ClusterIP (internal), NodePort (30000-32767), LoadBalancer (cloud LB), ExternalName (CNAME), Headless (clusterIP:None).','Service selector must match pod labels EXACTLY -- case-sensitive, key AND value. Empty endpoints = selector mismatch. Verify: kubectl get pods --show-labels.','kube-proxy implements Services via iptables DNAT rules rewriting ClusterIP:port to pod IP:targetPort. Conntrack ensures return packets are correctly un-DNATed.','NodePort is simplest external access but not for production. Each NodePort consumes one port cluster-wide. Prefer LoadBalancer + Ingress for HTTP workloads.','ExternalName creates CNAME to external DNS, providing abstraction. Change external endpoint without updating app code. Used for managed DBs, external APIs.','Headless Service (clusterIP:None) returns individual pod IPs via DNS. Required for StatefulSets needing stable network identity per pod.','EndpointSlices replace Endpoints for scalability, splitting large lists into chunks. Reduces watch overhead on kube-proxy. Max 100 endpoints per slice.','Session affinity (sessionAffinity:ClientIP) sends same client to same pod. Timeout configurable. Implemented via conntrack or IPVS persistence.','Service type determines traffic chain: ClusterIP = DNAT only, NodePort = KUBE-NODEPORTS DNAT, LoadBalancer = external infra + NodePort.','kube-proxy IPVS mode recommended for >1000 services. IPVS uses kernel hash table for O(1) lookup vs iptables O(n) rule traversal. Supports rr, lc, sh, dh schedulers.')
    'ch19' = @('Ingress routes external HTTP/HTTPS by host/path. Requires Ingress Controller (nginx, Traefik). Annotations configure TLS, CORS, rate limiting. Gateway API is the modern replacement.','Ingress Controller is a pod that watches Ingress resources and configures itself. Popular: ingress-nginx (K8s project), Traefik, HAProxy, Contour.','TLS termination at Ingress: controller decrypts HTTPS, forwards HTTP to Service. Cert stored in Secret. cert-manager automates certificate lifecycle.','Path routing: /api/* to jobpost-service, /admin/* to admin-service. Host routing: api.example.com vs admin.example.com. First match wins (longest path prefix).','Default backend handles unmatched requests. Without it, returns 404. Set via defaultBackend in Ingress spec for custom 404 pages or catch-all routing.','Annotations are controller-specific. nginx: rate limiting, CORS, SSL redirect, proxy buffers. Gateway API replaces annotations with standardized API fields.','TLS passthrough forwards encrypted traffic directly to backend without decryption. Requires SNI-based routing. Useful when backend handles its own mTLS.','IngressClassName selects which controller handles the resource. Multiple controllers coexist with different classes. Default class via annotation.','Health checks: controller probes backend health. Failed pods removed from upstream. Configured via annotations or backend protocol settings.','Gateway API supersedes Ingress: role-oriented (Gateway=ops, HTTPRoute=dev), native traffic splitting for canary, TCP/UDP routing, header-based matching.')
    'ch20' = @('CoreDNS is default K8s cluster DNS, running as Deployment in kube-system. Resolves service.ns.svc.cluster.local to ClusterIP. Config via Corefile ConfigMap.','Pod DNS: /etc/resolv.conf with nameserver=CoreDNS ClusterIP, search=ns.svc.cluster.local, options ndots:5. ndots controls when search domains are appended.','ndots:5 means names with <5 dots get search domains appended first. Can cause excessive queries for external names. Tune lower if apps mostly talk externally.','DNS policy per pod: Default, ClusterFirst (CoreDNS), ClusterFirstWithHostNet, None. Set via dnsPolicy in Pod spec.','Custom DNS via dnsConfig in Pod spec overrides /etc/resolv.conf. Add custom nameservers, searches, options for specific DNS requirements.','Stub domains forward specific domains to different DNS servers via Corefile: example.com { forward . 10.0.0.53 }. Essential for hybrid cloud DNS.','CoreDNS cache plugin caches responses for TTL duration. Default 10000 entries. Reduces latency and upstream query volume. Tune based on cluster query patterns.','NXDOMAIN (no such domain) vs SERVFAIL (server failure). Check CoreDNS logs: kubectl logs -n kube-system deployment/coredns. SERVFAIL often upstream DNS issue.','NodeLocal DNSCache runs DNS cache on each node, intercepting pod queries via iptables. Dramatically reduces CoreDNS load. Recommended for >100 node clusters.','CoreDNS listens on both UDP and TCP 53. Large responses use TCP. Zone transfers (AXFR) use TCP. NetworkPolicy must allow BOTH protocols for full DNS functionality.')
    'ch21' = @('NetworkPolicy controls pod-to-pod communication at L3/L4. Requires CNI support (Calico, Cilium, Weave). Additive: if ANY policy selects a pod, only allowed traffic passes.','Default-deny: empty podSelector:{} with no ingress/egress. Blocks ALL traffic. Must explicitly allow DNS (UDP 53), API server (TCP 443), and required services afterward.','podSelector:{} = ALL pods in namespace. namespaceSelector:{} = ALL namespaces. Empty selector = wildcard. Both must match for cross-namespace traffic.','Ingress controls inbound traffic TO pod. Egress controls outbound traffic FROM pod. policyTypes determines which directions are controlled.','ipBlock with except: allows CIDR while excluding subnets. Useful for allowing external egress (0.0.0.0/0) while blocking internal private IPs for SSRF prevention.','NetworkPolicy is namespace-scoped. Cross-namespace traffic needs namespaceSelector. Labels are the foundation -- plan label strategy before implementing policies.','Labels drive NetworkPolicy: each rule uses podSelector AND namespaceSelector. Both must match. Mismatched labels = silently dropped traffic.','Testing: kubectl exec pod -- nc -zv TARGET PORT. Test before and after applying. Use tcpdump inside pod to see dropped packets. Calico/Cilium provide policy tracing.','Calico adds global policies (cross-namespace), L7 rules (HTTP method/path), DNS rules, service account rules beyond standard NetworkPolicy.','Cilium adds L7 policies via eBPF: HTTP method/path/headers, Kafka topic, gRPC method. Hubble provides real-time flow observability with policy reason for drops.')
    'ch22' = @('Service Mesh adds mTLS, retries, timeouts, circuit breaking, observability without app changes. Sidecar proxy injected into each pod. Istio, Linkerd, Cilium are main options.','mTLS: both client AND server present certificates. Every pod-to-pod connection authenticated. SPIFFE identities: spiffe://cluster.local/ns/default/sa/pod-sa. Zero-trust foundation.','Sidecar injection: MutatingWebhook adds sidecar container. Init container creates iptables rules redirecting all traffic through sidecar: inbound port 15006, outbound port 15001.','Traffic splitting enables canary: 90% v1, 10% v2. Istio VirtualService+DestinationRule or Gateway API HTTPRoute with backendRefs weights. Gradual rollout with automated rollback.','Circuit breaking stops sending traffic to failing backends. Configurable: max connections, pending requests, retries, detection interval. Prevents cascading failures.','Retries automatically retry failed requests but amplify load on struggling backends. Always combine with circuit breaking. Configurable attempts, perTryTimeout, retryOn conditions.','Observability is automatic: request rate, latency, error rate, distributed tracing, access logs. All generated by sidecar proxy without application code changes.','Cilium sidecar-free mesh uses eBPF instead of sidecar containers. Lower resource overhead. mTLS via WireGuard/IPsec at kernel level. Hubble for observability.','Istio architecture: istiod (control plane) manages Envoy proxies (data plane) via xDS APIs. Gateway for ingress/egress at mesh edge.','Debugging mesh: kubectl logs pod -c istio-proxy. Check iptables rules in pod netns. Connection refused often = sidecar not ready. Add startupProbe or increase initialDelaySeconds.')
    'ch23' = @('Gateway API is next-gen K8s networking API: GatewayClass (infra provider), Gateway (cluster operator), HTTPRoute/TCPRoute (app developer). Role-oriented design separates concerns.','GatewayClass defines which controller implements Gateways. Similar to IngressClass. Cluster-scoped, managed by infrastructure provider.','Gateway configures listeners (HTTP, HTTPS, TLS), addresses, allowed routes. Managed by cluster operator. Multiple Gateways can coexist with different classes.','HTTPRoute: path matching (Prefix, Exact, Regex), header matching, query matching, method matching. Backend refs with weights. Filters for request/response modification.','TCPRoute/UDPRoute enables L4 routing for non-HTTP protocols. Routes TCP/UDP streams to backend Services. For databases, message queues, gaming servers.','Traffic splitting: multiple backendRefs with weights (90/10 canary). Header-based routing (beta users to v2). More expressive and portable than Ingress canary annotations.','Request/response modification: add/remove/set headers, rewrite paths, redirect. Filters applied in order. Standardized replacement for dozens of Ingress annotations.','Gateway API is extensible: custom route types, custom filters, policy attachment. Growing ecosystem: Istio, Contour, nginx, HAProxy, Cilium, Traefik, major cloud providers.','API maturity: GatewayClass, Gateway, HTTPRoute GA in v1.0. TCPRoute, TLSRoute at various stages. Active development with growing adoption.','Migration from Ingress: run both side-by-side. Gradual migration per service. Tools like ingress2gateway assist. Gateway API is the strategic direction -- invest now.')
}

# Process each chapter
$orphanCount = 0
foreach ($ch in 5,6,7,8,9,10,18,19,20,21,22,23) {
    $idx = $html.IndexOf("Chapter $ch ")
    if ($idx -lt 0) { continue }
    
    $nextCh = if ($ch -lt 38) { $ch + 1 } else { 999 }
    $nextIdx = $html.IndexOf("Chapter $nextCh ", $idx + 1)
    if ($nextIdx -lt 0) { $nextIdx = $idx + 100000 }
    
    $block = $html.Substring($idx, [Math]::Min($nextIdx - $idx, 100000))
    $items = [regex]::Matches($block, '(?s)<div class="exam-question-item">(.*?)</details>\s*</div>')
    
    $chKey = "ch$ch"
    $exps = $topics[$chKey]
    if (-not $exps) { Write-Host "Ch $ch : no topic data"; continue }
    
    $chOrphans = 0
    foreach ($item in $items) {
        if ($item.Value -match 'eq-explanation') { continue }
        
        $oldText = $item.Value
        $ansEnd = $oldText.LastIndexOf('</div>')
        if ($ansEnd -lt 0) { continue }
        
        $expIdx = $chOrphans % 10
        $expText = $exps[$expIdx]
        
        $before = $oldText.Substring(0, $ansEnd)
        $after = $oldText.Substring($ansEnd)
        $newText = $before + '<div class="eq-explanation"><div class="eq-exp-label">Explanation</div><p>' + $expText + '</p></div>' + $after
        
        $html = $html.Replace($oldText, $newText)
        $chOrphans++
        $orphanCount++
    }
    Write-Host "Ch $($ch.ToString().PadLeft(2)) : $chOrphans orphans fixed"
}

Set-Content $f $html -NoNewline
$sz1 = [math]::Round($html.Length/1KB,0)
Write-Host "Done. $sz0 -> $sz1 KB | Total orphans fixed: $orphanCount"
