$f = "KCSA.html"
$c = [System.IO.File]::ReadAllText((Resolve-Path $f))

function Get-Chapter($num) {
    $startTag = "id=`"ch$num`""
    $endTag = if ($num -eq 25) { "id=`"appendix-a`"" } else { "id=`"ch$($num+1)`"" }
    $s = $c.IndexOf($startTag)
    $e = $c.IndexOf($endTag, $s)
    if ($s -lt 0 -or $e -le $s) { return $null }
    return @{ start = $s; end = $e; text = $c.Substring($s, $e - $s) }
}

function Find-InsertPoint($chText, $chStart) {
    $lastSolutionClose = $chText.LastIndexOf("</details></div>")
    if ($lastSolutionClose -lt 0) { return -1 }
    return $chStart + $lastSolutionClose + "</details></div>".Length
}

function Add-ChapterQs($chNum, $qPairs) {
    $ch = Get-Chapter $chNum
    if ($null -eq $ch) { Write-Host "Ch$chNum`: NOT FOUND"; return }
    $insertAt = Find-InsertPoint $ch.text $ch.start
    if ($insertAt -lt 0) { Write-Host "Ch$chNum`: NO DRILL"; return }
    $insertText = ""
    foreach ($pair in $qPairs) { $insertText += "`n" + $pair[0] + "`n" + $pair[1] }
    $script:c = $c.Substring(0, $insertAt) + $insertText + $c.Substring($insertAt)
    Write-Host "Ch$chNum`: +$($qPairs.Count) Qs (pos $insertAt)"
}

# Ch12: +6 - Network Policies
$q=@()
$q+=,@('                    <div class="drill-scenario"><h5>Q5: What is the difference between ipBlock and podSelector in NetworkPolicy rules?</h5><ol><li>No difference — identical function</li><li>ipBlock filters by CIDR ranges for external IPs; podSelector filters by pod labels for internal K8s pods</li><li>podSelector only works for external traffic</li><li>ipBlock is deprecated</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. External CIDR vs internal labels.</strong> ipBlock selects traffic by IP ranges (external to cluster). podSelector and namespaceSelector select by K8s labels (internal pods). Combine all three in a single rule for precise control.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q6: What advantage do CiliumNetworkPolicies with FQDN egress provide?</h5><ol><li>Faster pod startup</li><li>Allow egress to specific domain names — CNI dynamically resolves DNS and updates allowed IPs</li><li>Better CPU performance</li><li>Automatic pod scaling</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Domain-based allowlisting.</strong> FQDN policies allow egress by domain name instead of IP. The CNI resolves DNS and auto-updates allowed IPs — critical for cloud APIs with changing IPs. Standard K8s NetworkPolicies cannot do this.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q7: What is micro-segmentation in Kubernetes?</h5><ol><li>Splitting clusters physically</li><li>Dividing pods into security zones (DMZ/App/Data) with strict NetworkPolicies between each zone</li><li>Using smaller container images</li><li>Running fewer pods per node</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Security zone isolation.</strong> Micro-segmentation creates zones where traffic flows only through defined paths. Compromise in one zone cannot spread laterally. DMZ->App->Data is the classic 3-tier pattern.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q8: What does podSelector: {} with policyTypes: [Ingress, Egress] and NO rules achieve?</h5><ol><li>Allows all traffic</li><li>Default-deny-all — blocks ALL ingress AND egress for every pod in the namespace</li><li>Only blocks ingress</li><li>No effect — NetworkPolicies need explicit rules</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Total network isolation.</strong> Empty podSelector applies to all pods. With both policyTypes set but no rules, ALL traffic is denied. Always add DNS egress exception to kube-system.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q9: How do you allow traffic from pods in namespaces labeled env=prod?</h5><ol><li>namespaceSelector: {}</li><li>namespaceSelector: {matchLabels: {env: prod}}</li><li>podSelector: {matchLabels: {env: prod}}</li><li>ipBlock: {cidr: 0.0.0.0/0}</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. namespaceSelector with matchLabels.</strong> namespaceSelector filters by NAMESPACE labels, not pod labels. This allows traffic from ALL pods within namespaces labeled env=prod.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q10: Why is Flannel insufficient for production security?</h5><ol><li>Too expensive</li><li>Flannel does NOT support NetworkPolicy enforcement — zero pod-to-pod isolation possible</li><li>Only runs on specific Linux versions</li><li>Too slow for production workloads</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. No NetworkPolicy support.</strong> Flannel only provides basic overlay networking. Without NetworkPolicy enforcement, you cannot restrict ANY pod-to-pod traffic. Use Calico, Cilium, or Weave Net for production.</p></details></div>')
Add-ChapterQs 12 $q

# Ch13: +6 - Audit Logging
$q=@()
$q+=,@('                    <div class="drill-scenario"><h5>Q5: What information does the Metadata audit level capture?</h5><ol><li>Complete request and response bodies</li><li>Who (user), What (verb/resource), When (timestamp), Where (source IP), and HTTP response code</li><li>Only timestamps</li><li>Only error codes</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Core forensic 5-tuple.</strong> Metadata captures user, verb, resource, namespace, source IP, and response code — enough for most forensics with minimal performance overhead. Use RequestResponse only for sensitive resources like Secrets.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q6: Which audit backend is best for real-time SIEM integration?</h5><ol><li>Local log file</li><li>Webhook backend — pushes audit events as HTTP POST to external collectors</li><li>Stdout streaming</li><li>All backends are equivalent</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Webhook backend.</strong> The webhook backend pushes audit events in real-time via HTTP to Splunk, ELK, or Datadog. Log file requires additional log shippers to collect and forward.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q7: Why use RequestResponse audit level specifically for Secret access?</h5><ol><li>Required by K8s standards</li><li>To capture exactly WHICH Secret was read and its contents — critical for breach forensics</li><li>Less disk usage than Metadata</li><li>No reason — Metadata is always enough</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Full Secret access trail.</strong> Metadata only shows someone read a secret. RequestResponse captures which specific secret and its contents. During a breach investigation, this tells you exactly what data was exposed.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q8: What happens if audit log disk fills with no rotation?</h5><ol><li>Oldest logs auto-delete</li><li>API server stops accepting requests — cluster outage</li><li>Logs auto-compress</li><li>Logs redirect to cloud storage</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Cluster outage.</strong> If the audit log disk fills completely, kube-apiserver stops. Always configure --audit-log-maxsize, --audit-log-maxbackup, and --audit-log-maxage for automatic rotation.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q9: At which stage is a request captured AFTER authentication?</h5><ol><li>ResponseComplete</li><li>RequestReceived — captured after authentication and authorization, before admission</li><li>ResponseStarted</li><li>Panic</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. RequestReceived.</strong> The audit pipeline stages: RequestReceived (after AuthN/AuthZ) -> ResponseStarted (headers sent) -> ResponseComplete (body sent) -> Panic (request caused panic).</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q10: What is the recommended audit log pipeline for compliance?</h5><ol><li>Keep logs on API server disk only</li><li>API server -> Fluent Bit DaemonSet -> Loki/ELK/Splunk for search -> S3/GCS for archival retention</li><li>Delete logs after 24 hours</li><li>Email daily log summaries</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Centralized pipeline with archival.</strong> Audit logs are forensic evidence. Ship via Fluent Bit to centralized platform for real-time search, then archive to object storage for long-term compliance (1-7 years depending on framework).</p></details></div>')
Add-ChapterQs 13 $q

# Ch14: +5 - Trust Boundaries
$q=@()
$q+=,@('                    <div class="drill-scenario"><h5>Q6: What security control should protect the namespace boundary?</h5><ol><li>RBAC</li><li>NetworkPolicies with namespaceSelector to restrict cross-namespace traffic</li><li>PodSecurityStandards</li><li>Secrets encryption</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. NetworkPolicies.</strong> By default, any pod can reach any pod across namespaces. NetworkPolicies with namespaceSelector enforce the namespace boundary by restricting which namespaces can communicate.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q7: Which encryption protects data in transit between pods?</h5><ol><li>EncryptionConfiguration</li><li>mTLS via service mesh (Istio/Linkerd/Cilium)</li><li>KMS envelope encryption</li><li>Base64 encoding</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. mTLS via service mesh.</strong> Service meshes automatically encrypt pod-to-pod traffic with mutual TLS. EncryptionConfiguration protects data at rest in etcd. KMS is for key management, not transit encryption.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q8: What does zero-trust networking mean in Kubernetes?</h5><ol><li>No firewalls needed</li><li>Never trust internal traffic — always authenticate and encrypt every communication hop</li><li>Trust all pods within the same namespace</li><li>Only external traffic needs authentication</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Verify every hop.</strong> Zero-trust means even internal pod-to-pod traffic is authenticated (SPIFFE identity) and encrypted (mTLS). No implicit trust based on network location. Every request is verified.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q9: Data stored in a PersistentVolume is in which state?</h5><ol><li>In transit</li><li>At rest</li><li>In use</li><li>In memory only</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. At rest.</strong> PV data is data at rest (on disk). Encrypt via CSI driver parameters (AWS EBS encrypted=true). Data in transit = TLS/mTLS. Data in use = in memory/processing.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q10: What defines a trust boundary crossing in Kubernetes?</h5><ol><li>Any pod restart</li><li>Any communication that crosses from one security zone to another — requires security controls at crossing point</li><li>Node reboots</li><li>Configuration changes</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Zone crossing.</strong> A trust boundary is crossed whenever traffic or data moves between security zones (external->DMZ, DMZ->App, App->Data). Each crossing needs specific controls: TLS, mTLS, NetworkPolicy, authentication.</p></details></div>')
Add-ChapterQs 14 $q

# Ch15: +5 - Attack Vectors
$q=@()
$q+=,@('                    <div class="drill-scenario"><h5>Q6: What is the escalation chain after compromising a container?</h5><ol><li>Container -> pod -> namespace -> nothing else</li><li>Container -> if privileged:true -> host root -> kubelet credentials -> full cluster compromise</li><li>Container -> immediate cluster-admin</li><li>Container -> network access only</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Full escalation chain.</strong> A compromised privileged container gives host root access. From there, attacker steals kubelet credentials (in /var/lib/kubelet) and impersonates the node to the API server. PSS Restricted blocks this entire chain.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q7: How does API Priority and Fairness (APF) mitigate DoS?</h5><ol><li>It blocks all external traffic</li><li>It categorizes requests into priority levels and ensures fair queue distribution — critical system requests always get through</li><li>It increases CPU allocation</li><li>It restarts crashed pods</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Priority-based queuing.</strong> APF assigns priority levels to API requests. During heavy load, critical requests (system:nodes, kubelet) get processed while low-priority requests (user queries) are throttled. Prevents one noisy tenant from DoS-ing the API server.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q8: What is the most common persistence mechanism after K8s compromise?</h5><ol><li>Deleting all pods</li><li>Creating a backdoor DaemonSet or malicious admission webhook that survives restarts</li><li>Restarting the API server</li><li>Changing pod labels</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Backdoor DaemonSet or webhook.</strong> Attackers create DaemonSets (run on every node, survive reboots) or admission webhooks (intercept all future requests). Mitigate with Kyverno policies auditing DaemonSet creation and webhook changes.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q9: How does readOnlyRootFilesystem prevent post-exploitation?</h5><ol><li>It blocks network access</li><li>Attacker cannot install rootkits, download tools, modify binaries, or plant backdoors</li><li>It prevents CPU usage</li><li>It blocks all file access</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Blocks tool installation.</strong> With readOnlyRootFilesystem:true, the container filesystem is immutable. Even if attacker gets a shell, they cannot install netcat, cryptominers, or modify system files. Only mounted volumes remain writable.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q10: What defense prevents lateral movement between compromised and healthy pods?</h5><ol><li>RBAC</li><li>NetworkPolicies with micro-segmentation + mTLS service mesh</li><li>PodSecurityStandards</li><li>Secrets encryption</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. NetworkPolicies + mTLS.</strong> NetworkPolicies restrict which pods can communicate (who can talk to whom). mTLS ensures even allowed connections are authenticated and encrypted. Together they prevent lateral movement.</p></details></div>')
Add-ChapterQs 15 $q

# Ch16: +6 - Threat Modeling
$q=@()
$q+=,@('                    <div class="drill-scenario"><h5>Q5: STRIDE: Which category covers an attacker reading Secrets from etcd?</h5><ol><li>Spoofing</li><li>Information Disclosure</li><li>Denial of Service</li><li>Elevation of Privilege</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Information Disclosure.</strong> Unauthorized access to Secrets = Information Disclosure. Spoofing = pretending to be someone else. Elevation = gaining higher privileges.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q6: In DREAD, what does "Reproducibility" measure?</h5><ol><li>How many users affected</li><li>How consistently the attack can be repeated — 10 means always reproducible</li><li>How much damage caused</li><li>How easy to discover</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Consistency of reproduction.</strong> Reproducibility scores how reliably the attack works. 10 = always reproducible with a script. 1 = extremely difficult to reproduce even once.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q7: What is the formula for risk in threat modeling?</h5><ol><li>Risk = CVSS score only</li><li>Risk = Likelihood x Impact — prioritize threats with highest product</li><li>Risk = number of vulnerabilities</li><li>Risk = DREAD score / 10</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Likelihood x Impact.</strong> Risk is the product of how likely an attack is AND how severe the impact. A highly likely but low-impact threat may be lower priority than an unlikely but catastrophic one.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q8: Which STRIDE category does a compromised CI/CD pipeline fall under?</h5><ol><li>Spoofing</li><li>Tampering</li><li>Information Disclosure</li><li>Denial of Service</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Tampering.</strong> Modifying the build pipeline to inject malicious code = Tampering. Mitigated by SLSA provenance, image signing (Cosign), and admission control verification.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q9: What does an attack tree''s leaf node represent?</h5><ol><li>The attacker''s ultimate goal</li><li>A specific attack technique with risk score = likelihood x impact</li><li>A mitigation strategy</li><li>The root cause</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Specific attack technique.</strong> Root node = goal. Branches = intermediate steps. Leaf nodes = specific attacks, each scored by likelihood and impact. Prioritize mitigations for highest-risk leaves.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q10: STRIDE + DREAD together provide what?</h5><ol><li>Just threat identification</li><li>STRIDE identifies threats by category; DREAD scores and prioritizes them by risk</li><li>Only compliance reporting</li><li>Incident response procedures</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Identification + prioritization.</strong> STRIDE categorizes threats (what could go wrong). DREAD scores each threat numerically (how bad is it). Together = complete threat model: identify THEN prioritize.</p></details></div>')
Add-ChapterQs 16 $q

# Ch17: +6 - Incident Response
$q=@()
$q+=,@('                    <div class="drill-scenario"><h5>Q5: In the NIST IR lifecycle, what comes after Detection?</h5><ol><li>Eradication</li><li>Containment — isolate the threat BEFORE eradication</li><li>Recovery</li><li>Lessons Learned</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Containment before eradication.</strong> NIST order: Prepare->Detect->Contain->Eradicate->Recover->Learn. Always contain first to stop the spread. Eradicating without containment allows lateral movement.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q6: How do you contain a compromised pod in K8s?</h5><ol><li>Delete it immediately</li><li>Apply emergency NetworkPolicy denying all egress from the pod</li><li>Ignore it — K8s auto-heals</li><li>SSH into the node and kill the process</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Emergency NetworkPolicy.</strong> Apply a NetworkPolicy that blocks all egress from the compromised pod FIRST (containment), THEN collect forensic evidence (logs, events, etcd snapshot), THEN delete the pod (eradication).</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q7: What forensic evidence should you collect before eradicating a compromised pod?</h5><ol><li>Nothing — just delete it</li><li>Pod logs (kubectl logs), pod description (kubectl describe), cluster events, and etcd snapshot</li><li>Only the pod name</li><li>Only network logs</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Full forensic snapshot.</strong> Collect kubectl logs, kubectl describe, kubectl get events, and etcd snapshot BEFORE deleting anything. Preserve chain of custody. Store in secure, immutable storage.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q8: After eradicating a compromised pod, what must you do before redeploying?</h5><ol><li>Nothing — just redeploy</li><li>Rotate ALL Secrets and credentials the pod had access to</li><li>Rename the namespace</li><li>Restart the node only</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Rotate all credentials.</strong> Assume all Secrets and tokens the pod accessed are compromised. Rotate SA tokens, DB passwords, API keys, and TLS certificates before redeploying from a known-good signed image.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q9: Which Falco rule detects lateral movement?</h5><ol><li>Shell spawn in container</li><li>Unexpected outbound network connection from a container to unknown IPs</li><li>File read in container</li><li>Process creation</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Unexpected outbound connections.</strong> Falco detects when a container connects to IPs outside its expected communication pattern (e.g., web pod suddenly connecting to a database it shouldn''t access). This indicates lateral movement.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q10: What is the value of an etcd snapshot during incident response?</h5><ol><li>It restarts pods</li><li>It captures the complete cluster state at the moment of the incident — all objects, secrets, and configurations</li><li>It only backs up Secrets</li><li>It has no forensic value</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Complete state snapshot.</strong> An etcd snapshot during an incident captures exactly what resources existed, what Secrets were present, and what RBAC was configured at that moment. Critical forensic evidence for root cause analysis.</p></details></div>')
Add-ChapterQs 17 $q

[System.IO.File]::WriteAllText((Resolve-Path $f), $c)
Write-Host "Ch12-17 done. Size: $([math]::Round($c.Length/1024,1))KB"