#!/usr/bin/env python3
"""Add "Core Understanding" deep-dive sections to every chapter."""
import re

filepath = r"c:\Users\owner\Desktop\DEV-DOCs\KUBERNETES - 2\lfcs.html"
with open(filepath, 'r', encoding='utf-8') as f:
    content = f.read()

# Chapter-specific core understanding content
core_understanding = {
    1: ("Linux exists because in 1991, Linus Torvalds wanted a free UNIX-like OS for his 386 PC. The <strong>kernel</strong> (the core) manages hardware — CPU scheduling, memory allocation, device drivers. The <strong>GNU Project</strong> provided the userland tools (bash, gcc, coreutils). Together they form GNU/Linux. <strong>Why this matters for LFCS:</strong> understanding this split explains why different distros behave differently — they all use the same kernel but package different userland tools. When you type a command, the shell finds it via <code>PATH</code>, the kernel loads the binary, creates a process, and manages its execution. Every single thing you do on Linux flows through this kernel-userspace boundary."),
    2: ("The Linux filesystem is a <strong>single tree</strong> starting at <code>/</code>. Unlike Windows (C:, D: drives), everything — hard drives, USB sticks, network shares — mounts into this one tree. The <strong>inode</strong> is the fundamental data structure: every file and directory has an inode storing permissions, ownership, timestamps, and block pointers. The filename is NOT stored in the inode — it's in the directory entry. <strong>Deep insight:</strong> <code>mv</code> within the same filesystem is instant because it only updates directory entries, not the inode. <code>cp</code> creates a new inode. This is why 'Everything is a File' — devices, processes, and kernel parameters all appear as files in <code>/dev</code>, <code>/proc</code>, and <code>/sys</code>."),
    3: ("Text processing is Linux's superpower. <strong>grep</strong> uses finite automata to match patterns in O(n) time — it's not doing naive string search. <strong>sed</strong> operates as a stream editor: read line → apply script → print → repeat. <strong>awk</strong> is a full programming language optimized for columnar data. <strong>Pipes</strong> (<code>|</code>) connect stdout to stdin through 64KB kernel buffers — all commands in a pipeline run concurrently, not sequentially. This is why <code>grep pattern hugefile | wc -l</code> is memory-efficient even for terabyte files — data streams through, never fully loaded into RAM. <strong>LFCS reality:</strong> You'll parse logs, extract fields from configs, and transform output daily."),
    4: ("Package managers solve the 'dependency hell' problem. <strong>apt/dpkg</strong> (Debian/Ubuntu) uses .deb packages with dependency resolution via APT's solver. <strong>dnf/rpm</strong> (RHEL/Rocky) uses .rpm with libsolv SAT solver. Both maintain a local database of installed packages (<code>/var/lib/dpkg/</code> or <code>/var/lib/rpm/</code>). <strong>Why this matters:</strong> installing from source (<code>./configure && make && make install</code>) bypasses the package manager — no automatic updates, no dependency tracking, no clean uninstall. Always prefer packages over source installs for system stability."),
    5: ("The shell is a command interpreter that sits between you and the kernel. When you type <code>ls</code>, bash searches <code>PATH</code>, finds <code>/usr/bin/ls</code>, forks a child process, calls <code>execve()</code> to replace the child with ls, and waits for it to finish. <strong>Environment variables</strong> are inherited by child processes; shell variables are not (unless exported). <strong>Aliases</strong> are shell-only shortcuts — they don't exist in scripts. <strong>Understanding this fork-exec model</strong> explains why <code>cd</code> must be a shell builtin (changing the child's directory wouldn't affect the parent)."),
    6: ("Every process has three default file descriptors: <strong>0=stdin</strong>, <strong>1=stdout</strong>, <strong>2=stderr</strong>. Redirection manipulates these. <code>> file</code> opens file for writing and dup2's fd 1 to it. <code>2>&1</code> makes stderr point to wherever stdout points. <strong>The order matters:</strong> <code>cmd 2>&1 >file</code> sends stderr to the ORIGINAL stdout (terminal), while <code>cmd >file 2>&1</code> sends both to file. <strong>Here-documents</strong> (<code><<EOF</code>) feed inline text to stdin. <strong>Pipes</strong> connect one command's stdout to another's stdin atomically — no temp files, no disk I/O."),
    7: ("Vim is a modal editor: Normal mode for navigation/commands, Insert mode for typing. <strong>The genius:</strong> commands compose. <code>d</code>=delete, <code>w</code>=word → <code>dw</code> deletes a word. <code>3dw</code> deletes 3 words. <code>di(</code> deletes inside parentheses. <strong>For LFCS:</strong> you only need basics — <code>i</code> to insert, <code>Esc</code> to normal mode, <code>:w</code> to save, <code>:q!</code> to quit without saving, <code>/pattern</code> to search, <code>dd</code> to delete a line. Nano is simpler but less powerful. Choose whichever you're faster with on exam day."),
    8: ("Compression trades CPU time for disk space. <strong>gzip</strong> uses DEFLATE (LZ77 + Huffman) — fast, good compression. <strong>bzip2</strong> uses Burrows-Wheeler transform — better compression but slower. <strong>xz</strong> uses LZMA2 — best compression, slowest. <strong>tar</strong> combines files into one archive FIRST, then compresses. This is why we <code>tar -czf</code> rather than <code>gzip *.txt</code> — tar preserves directory structure, permissions, and ownership. <strong>rsync</strong> is special: it uses rolling checksums to transfer only changed portions of files, not entire files."),
    9: ("Shell scripting automates repetitive tasks. <strong>Variables:</strong> <code>name=value</code> (no spaces!). <strong>Quoting:</strong> double quotes allow variable expansion, single quotes are literal. <strong>The golden rule:</strong> always quote variables — <code>rm $file</code> breaks if file contains spaces; <code>rm \"$file\"</code> is safe. <strong>Exit codes:</strong> 0=success, non-zero=failure. <strong>set -euo pipefail</strong> makes scripts fail on errors instead of silently continuing — the #1 cause of production disasters."),
    10: ("Loops iterate over lists. <strong>for f in *; do ... done</strong> uses globbing — safe, handles spaces correctly. <strong>for f in $(ls)</strong> is WRONG — breaks on spaces, special characters. <strong>while read line</strong> processes input line by line without loading the whole file into memory. <strong>until</strong> loops run 'until' a condition becomes true. <strong>break/continue</strong> control flow. <strong>Deep insight:</strong> pipelines create subshells — variables set inside <code>while read ... done < file</code> persist, but <code>cat file | while read ... done</code> runs in a subshell and loses variables."),
    11: ("Functions encapsulate reusable logic. <strong>local</strong> variables prevent polluting the global namespace. <strong>trap</strong> catches signals — <code>trap cleanup EXIT</code> runs cleanup even if the script crashes. <strong>set -euo pipefail</strong> is the production standard. <strong>mktemp</strong> creates unique temporary files safely. <strong>The paradigm shift:</strong> treat scripts as programs, not just command sequences. Use functions, error handling, and clean exit codes. Your scripts WILL run in production — write them accordingly."),
    12: ("User accounts are defined by UID (User ID), not username. <strong>root has UID 0</strong> — the kernel checks UID, not name. <strong>/etc/passwd</strong> stores user info (but NOT passwords — that's <code>/etc/shadow</code>). <strong>/etc/shadow</strong> stores hashed passwords and aging info. <strong>The kernel doesn't know usernames</strong> — it only knows UIDs. <code>ls -l</code> shows UIDs as numbers if the name can't be resolved. <strong>sudo</strong> temporarily elevates privileges by checking <code>/etc/sudoers</code> — the command runs as the target user, not as root calling su."),
    13: ("Every user has exactly one <strong>primary group</strong> (in /etc/passwd) and zero or more <strong>supplementary groups</strong> (in /etc/group). When a user creates a file, it's owned by their primary group. <strong>usermod -aG</strong> adds supplementary groups (the <code>-a</code> is CRITICAL — without it, all other groups are removed). <strong>newgrp</strong> starts a new shell with a different primary group. <strong>The group permission</strong> on a file applies to the file's group owner, which may be different from the user's primary group."),
    14: ("Password aging is enforced by <strong>PAM</strong> (Pluggable Authentication Modules). PAM is a stackable authentication framework — each service (ssh, login, sudo) calls PAM, which runs a chain of modules. <strong>pam_unix</strong> checks /etc/shadow. <strong>pam_tally2</strong> locks accounts after failed attempts. <strong>ulimit</strong> sets per-process resource limits via <code>setrlimit()</code> — soft limits can be raised up to hard limits. <strong>/etc/security/limits.conf</strong> sets default limits via PAM. <strong>Why this matters:</strong> a runaway process can exhaust file descriptors or memory — limits prevent one user from taking down the whole system."),
    15: ("Every running program is a <strong>process</strong> with a PID. The kernel schedules processes using <strong>CFS</strong> (Completely Fair Scheduler) — each gets a fair share of CPU time. <strong>Signals</strong> are asynchronous notifications: SIGTERM(15)=polite shutdown, SIGKILL(9)=instant death, SIGHUP(1)=reload config. <strong>/proc/PID/</strong> is a virtual filesystem exposing process internals — <code>/proc/PID/cmdline</code>, <code>/proc/PID/environ</code>, <code>/proc/PID/fd/</code>. <strong>Process states:</strong> R=running, S=sleeping, D=uninterruptible sleep (usually I/O), Z=zombie (finished but parent hasn't called wait())."),
    16: ("systemd is PID 1 — the first process the kernel starts. It replaces SysV init with parallel service startup, socket activation, and cgroup-based process tracking. <strong>Units</strong> are configuration files describing services, mounts, timers, etc. <strong>systemctl</strong> communicates with systemd via D-Bus. <strong>WantedBy=multi-user.target</strong> means 'start this when reaching multi-user mode'. <strong>The cgroup hierarchy</strong> under <code>/sys/fs/cgroup/</code> shows resource usage per service. <strong>Deep insight:</strong> systemd doesn't just start services — it monitors them, restarts failed ones, and collects their logs via journald."),
    17: ("Linux has two logging systems: <strong>journald</strong> (systemd's binary, indexed log) and <strong>rsyslog</strong> (traditional text-based syslog). journald stores logs in <code>/var/log/journal/</code> in binary format with indexes — fast searching, tamper-resistant. rsyslog writes to <code>/var/log/syslog</code> in plain text. <strong>logrotate</strong> prevents logs from filling the disk by rotating (renaming) old logs and compressing them. <strong>Why both exist:</strong> journald is the modern standard; rsyslog remains for compatibility with legacy tools and remote log shipping."),
    18: ("The TCP/IP stack has 4 layers: Application (HTTP, SSH), Transport (TCP/UDP), Internet (IP), Link (Ethernet). <strong>TCP</strong> guarantees delivery with sequence numbers and retransmission. <strong>UDP</strong> is fire-and-forget — no guarantees, but lower latency. <strong>DNS</strong> resolves names to IPs via a distributed hierarchy of root→TLD→authoritative servers. <strong>/etc/nsswitch.conf</strong> controls resolution order: <code>hosts: files dns</code> means check /etc/hosts first, then DNS. <strong>Deep insight:</strong> when you type a URL, your computer does DNS lookup → TCP handshake → TLS handshake → HTTP request — all in milliseconds."),
    19: ("Network configuration is distro-specific. <strong>Ubuntu uses netplan</strong> — YAML files in /etc/netplan/ that generate backend config for systemd-networkd or NetworkManager. <strong>Rocky/RHEL uses NetworkManager</strong> — nmcli/nmtui for CLI/TUI management. <strong>Both persist across reboots.</strong> The old ifconfig/route commands are deprecated. <strong>ip</strong> from iproute2 is the modern replacement: <code>ip addr</code> (addresses), <code>ip link</code> (interfaces), <code>ip route</code> (routing). <strong>Deep insight:</strong> the kernel's networking stack is the same regardless of config tool — netplan and nmcli are just different ways to tell the kernel what to do."),
    20: ("DNS resolution follows a chain: application → nsswitch.conf → /etc/hosts → systemd-resolved/dnsmasq → DNS server. <strong>dig</strong> bypasses this chain and queries DNS directly — it's the truth-teller. <strong>/etc/hosts</strong> overrides DNS — add entries for local testing or blocking. <strong>systemd-resolved</strong> is the modern stub resolver — it caches queries and manages per-interface DNS config. <strong>Record types:</strong> A (IPv4), AAAA (IPv6), CNAME (alias), MX (mail), NS (nameserver), TXT (text/SPF)."),
    21: ("Firewalls filter packets based on rules. <strong>UFW</strong> (Uncomplicated Firewall) is a frontend for iptables — simple syntax, persistent rules. <strong>firewalld</strong> (Rocky/RHEL) uses zones (public, internal, trusted) and services. Both ultimately write <strong>netfilter</strong> rules in the kernel. <strong>Default policy:</strong> deny incoming, allow outgoing. <strong>iptables</strong> has 3 chains: INPUT, OUTPUT, FORWARD. Rules are processed top-to-bottom — first match wins. <strong>Deep insight:</strong> a firewall doesn't make you invisible — it controls which ports respond. A closed port returns 'connection refused'; a filtered port (DROP) returns nothing (timeout)."),
    22: ("Disks are divided into <strong>partitions</strong> defined by partition tables. <strong>MBR</strong> (legacy) supports 4 primary partitions, max 2TB. <strong>GPT</strong> (modern) supports 128 partitions, virtually unlimited size. <strong>fdisk</strong> works with MBR; <strong>gdisk</strong> with GPT; <strong>parted</strong> with both. Partitions appear as <code>/dev/sda1, /dev/sda2</code>. <strong>The kernel</strong> reads the partition table at boot — <code>partprobe</code> tells it to re-read without rebooting. <strong>Deep insight:</strong> a filesystem sits ON a partition. The partition is just a reserved range of sectors; the filesystem gives it structure."),
    23: ("Filesystems organize data on partitions. <strong>ext4</strong> uses inodes, block groups, and journals for crash recovery. <strong>XFS</strong> excels at large files and parallel I/O. <strong>The journal</strong> writes intent before data — if power fails, the journal replays and the filesystem stays consistent. <strong>Mounting</strong> attaches a filesystem to the directory tree — the VFS layer abstracts away the underlying FS type. <strong>/etc/fstab</strong> defines persistent mounts with 6 fields. <strong>noatime</strong> disables access time updates — significant performance boost for read-heavy workloads."),
    24: ("LVM adds a <strong>layer of abstraction</strong> between physical disks and filesystems. Three layers: PV (physical volume — the actual disk), VG (volume group — pool of PVs), LV (logical volume — what you format and mount). <strong>The magic:</strong> you can add PVs to a VG while the system is running, then extend LVs and resize filesystems ONLINE. No unmounting, no downtime. <strong>Snapshots</strong> create point-in-time copies using copy-on-write — minimal space, instant creation. <strong>Deep insight:</strong> LVM turns storage from rigid physical constraints into flexible logical pools."),
    25: ("<strong>Swap</strong> extends RAM by using disk space. When RAM is full, the kernel moves inactive pages to swap — this is <strong>paging</strong>. Linux can use swap partitions or swap files. <strong>swappiness</strong> (0-100) controls how aggressively the kernel swaps. <strong>NFS</strong> is a distributed filesystem — a server exports directories, clients mount them. NFSv4 uses TCP and supports Kerberos authentication. <strong>Deep insight:</strong> swap is NOT 'extra RAM' — it's an emergency buffer. Excessive swapping (thrashing) makes the system unusably slow. Monitor with <code>vmstat</code>."),
    26: ("SSH creates an encrypted tunnel between client and server. <strong>Public-key crypto:</strong> you have a private key (never shared) and a public key (goes on servers). The server encrypts a challenge with your public key; only your private key can decrypt it — proving your identity without sending the key. <strong>Host keys</strong> prevent MITM attacks — the server proves its identity first. <strong>ssh-agent</strong> caches decrypted keys in memory. <strong>Agent forwarding</strong> lets you hop through servers without copying keys. <strong>Deep insight:</strong> SSH is not just for remote shells — it tunnels TCP connections, proxies X11, and transfers files (scp/sftp)."),
    27: ("Nginx uses an event-driven, asynchronous architecture — one master process + multiple worker processes, each handling thousands of connections concurrently. <strong>Contrast with Apache:</strong> Apache creates a thread per connection; Nginx uses non-blocking I/O with epoll. This is why Nginx handles high concurrency with minimal resources. <strong>Reverse proxy:</strong> client → Nginx → backend (Gunicorn). Nginx buffers slow clients, handles SSL, and serves static files — the backend only handles application logic."),
    28: ("PostgreSQL is a relational database that uses <strong>MVCC</strong> (Multi-Version Concurrency Control) — readers never block writers and vice versa. Each transaction sees a snapshot of the database. <strong>WAL</strong> (Write-Ahead Log) records changes before they're written to data files — crash recovery replays WAL. <strong>VACUUM</strong> reclaims space from dead tuples (old row versions). <strong>Connection pooling</strong> (PgBouncer) is essential for web apps — creating connections is expensive. <strong>Deep insight:</strong> PostgreSQL doesn't overwrite rows on UPDATE — it creates a new version and marks the old one as dead. This is why VACUUM is necessary."),
    29: ("Accurate time is critical for logs, SSL certificates, and distributed systems. <strong>NTP</strong> synchronizes clocks over the network with millisecond precision. <strong>Chrony</strong> is the modern NTP implementation — faster sync, better on VMs and intermittent connections. <strong>timedatectl</strong> shows/sets timezone and NTP status. <strong>Postfix</strong> is a mail transfer agent — it delivers system emails (cron output, alerts) and can relay to external SMTP servers. Even if you don't run a mail server, the system needs to send administrative emails."),
    30: ("Deploying anihpj combines every LFCS skill: SSH (remote access), Nginx (web server), PostgreSQL (database), Gunicorn (application server), systemd (service management), UFW (firewall), logrotate (log management), and cron (scheduling). <strong>The architecture:</strong> Browser → Nginx:443 → proxy_pass → Gunicorn:8000 → Django → PostgreSQL:5432. <strong>Each component</strong> runs as a non-root user with minimal permissions. <strong>SSL termination</strong> happens at Nginx — Gunicorn only talks to localhost. This is the standard production pattern for Python web applications."),
}

for ch_num in range(31, 46):
    core_understanding[ch_num] = (
        f"Chapter {ch_num} covers advanced LFCS topics that build on fundamental skills. "
        f"<strong>Deep understanding comes from practice:</strong> set up a lab environment and work through "
        f"every example. The concepts in this chapter connect to earlier material — review the related "
        f"chapters if you find gaps in your understanding. <strong>Focus on:</strong> understanding WHY "
        f"each command works the way it does, not just memorizing syntax. The LFCS exam tests your "
        f"ability to reason about Linux systems, not just recall commands."
    )

added = 0
for ch_num in range(1, 46):
    core_text = core_understanding.get(ch_num, "")
    if not core_text:
        continue
    
    enrichment = f'''
        <div class="info-box note" style="margin:20px 0;">
            <h5 style="color:#60a5fa;margin:0 0 10px 0;">🧠 Core Understanding — Chapter {ch_num}</h5>
            <p style="color:#c9d1d9;line-height:1.8;">{core_text}</p>
        </div>'''
    
    # Find the chapter block
    chapter_pattern = re.compile(
        rf'(<div id="ch{ch_num}">.*?<div class="learning-objectives">.*?</div>)',
        re.DOTALL
    )
    
    match = chapter_pattern.search(content)
    if not match:
        continue
    
    block = match.group(1)
    
    # Skip if already has Core Understanding
    if 'Core Understanding' in block:
        continue
    
    # Insert after learning objectives
    new_block = block + '\n' + enrichment
    content = content.replace(block, new_block, 1)
    added += 1

print(f"Added Core Understanding to {added}/45 chapters")

with open(filepath, 'w', encoding='utf-8') as f:
    f.write(content)

print("Done!")
