$f = "KCSA.html"
$c = [System.IO.File]::ReadAllText((Resolve-Path $f))

function Get-Chapter($num) {
    $startTag = "id=`"ch$num`""
    $endTag = if ($num -eq 25) { "id=`"appendix-a`"" } else { "id=`"ch$($num+1)`"" }
    $s = $c.IndexOf($startTag)
    $e = $c.IndexOf($endTag, $s)
    if ($s -lt 0 -or $e -le $s) { return $null }
    return @{ start = $s; end = $e; text = $c.Substring($s, $e - $s) }
}
function Find-InsertPoint($chText, $chStart) {
    $l = $chText.LastIndexOf("</details></div>")
    if ($l -lt 0) { return -1 }
    return $chStart + $l + "</details></div>".Length
}
function Add-ChapterQs($chNum, $qPairs) {
    $ch = Get-Chapter $chNum
    if ($null -eq $ch) { Write-Host "Ch$chNum`: NOT FOUND"; return }
    $ia = Find-InsertPoint $ch.text $ch.start
    if ($ia -lt 0) { Write-Host "Ch$chNum`: NO DRILL"; return }
    $it = ""
    foreach ($p in $qPairs) { $it += "`n" + $p[0] + "`n" + $p[1] }
    $script:c = $c.Substring(0, $ia) + $it + $c.Substring($ia)
    Write-Host "Ch$chNum`: +$($qPairs.Count) Qs"
}

# Ch18: +4 - Supply Chain
$q=@()
$q+=,@('                    <div class="drill-scenario"><h5>Q7: What is the difference between SPDX and CycloneDX SBOM formats?</h5><ol><li>No difference</li><li>SPDX is ISO/IEC 5962:2021 standard by Linux Foundation; CycloneDX is OWASP standard optimized for security tools</li><li>CycloneDX is deprecated</li><li>SPDX is for images only</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. ISO vs OWASP standards.</strong> SPDX is the international standard (ISO), focused on license compliance. CycloneDX is OWASP''s format, focused on security/risk analysis with native VEX support. Both are valid SBOM formats.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q8: What does the Sigstore ecosystem provide for supply chain security?</h5><ol><li>Only image scanning</li><li>Keyless signing (Cosign), certificate authority (Fulcio), and transparency log (Rekor) — all using OIDC identity</li><li>Only vulnerability database</li><li>Only SBOM generation</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Complete signing ecosystem.</strong> Sigstore = Cosign (sign/verify) + Fulcio (OIDC-based CA) + Rekor (immutable transparency log). Enables keyless signing where OIDC identity proves who signed.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q9: What does VEX (Vulnerability Exploitability eXchange) tell you?</h5><ol><li>The CVSS score</li><li>Whether a CVE is actually exploitable in YOUR specific usage of the vulnerable component</li><li>How to exploit the vulnerability</li><li>The CVE publication date</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Context-specific exploitability.</strong> VEX supplements SBOMs. A CVE in Django''s PostgreSQL backend does not affect anihpj if it uses SQLite. VEX says "not exploitable" for YOUR specific configuration — eliminating false positives.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q10: Which tool generates SLSA provenance for GitHub Actions builds?</h5><ol><li>Cosign</li><li>SLSA GitHub Generator — creates verifiable attestations of the build process</li><li>Trivy</li><li>Syft</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. SLSA GitHub Generator.</strong> slsa-framework/slsa-github-generator creates cryptographically signed attestations proving what source was built, by which workflow, on which runner — achieving SLSA Level 2+ with minimal configuration.</p></details></div>')
Add-ChapterQs 18 $q

# Ch19: +7 - Image Repository
$q=@()
$q+=,@('                    <div class="drill-scenario"><h5>Q4: What is a distroless base image and why is it more secure?</h5><ol><li>A smaller image that builds faster</li><li>Contains NO shell, package manager, or utilities — attacker cannot run bash or install tools after compromise</li><li>An image without any OS</li><li>An image that only runs on specific hardware</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. No shell = no post-exploitation.</strong> Distroless images contain only the application and its runtime dependencies. No bash, no apt, no curl — an attacker with code execution cannot download tools or move laterally.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q5: What does the imagePullPolicy: Always admission controller enforce?</h5><ol><li>Pods pull images only from cache</li><li>Kubelet always contacts the registry on every pod start — prevents using stale or tampered cached images</li><li>Images never update</li><li>Only specific tags allowed</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Fresh pull every time.</strong> AlwaysPullImages ensures the kubelet checks the registry on every pod creation. This prevents attackers from exploiting a cached image that may have been tampered with on the node.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q6: Why should you use image@sha256 digests instead of tags in production?</h5><ol><li>Digests are shorter</li><li>Digests are immutable — :latest or :v1 could point to different images tomorrow. sha256:abc... uniquely identifies one exact image</li><li>Digests load faster</li><li>Tags are deprecated</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Immutable identity.</strong> Tags are mutable pointers. sha256 digests are content-addressable and immutable. Deploying by digest ensures you always run the exact same image that passed security scanning.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q7: What is the purpose of imagePullSecrets in a pod spec?</h5><ol><li>Encrypt pod logs</li><li>Provide registry credentials so kubelet can pull from private registries like ghcr.io/myorg</li><li>Sign container images</li><li>Scan images for vulnerabilities</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Private registry authentication.</strong> imagePullSecrets reference a kubernetes.io/dockerconfigjson Secret containing registry credentials. Without this, kubelet cannot pull from private registries.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q8: What is the advantage of multi-stage Docker builds for security?</h5><ol><li>Faster builds</li><li>Builder stage with compilers/tools is discarded — final image contains ONLY runtime artifacts, dramatically reducing attack surface</li><li>Smaller image tags</li><li>Multi-stage builds are faster</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Builder tools discarded.</strong> Multi-stage builds separate build environment (gcc, pip, git) from runtime. Build tools (common attack vectors) never appear in the final image. Result: smaller, more secure images with fewer CVEs.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q9: What does immutable tags in a registry prevent?</h5><ol><li>Image deletion</li><li>Tag-swapping attacks — once v1.0.0 is pushed, it can never be overwritten with a different image</li><li>Image scanning</li><li>Image pulling</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Tag-swapping attacks.</strong> Without immutable tags, an attacker could push a malicious image tagged v1.0.0 over the legitimate one. Immutable tags prevent overwrites — each tag points to exactly one image forever.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q10: Which admission policy should block :latest tag in production?</h5><ol><li>RBAC policy</li><li>Kyverno/OPA policy at admission — reject any pod using :latest tag</li><li>NetworkPolicy</li><li>PodSecurityStandard</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Kyverno/OPA admission policy.</strong> Admission controllers are the LAST gate before a pod is created. A Kyverno ClusterPolicy with validationFailureAction: Enforce can reject any pod using :latest tag — the pod never even starts.</p></details></div>')
Add-ChapterQs 19 $q

# Ch20: +6 - Observability
$q=@()
$q+=,@('                    <div class="drill-scenario"><h5>Q5: What does a spike in apiserver_request_total{code="403"} indicate?</h5><ol><li>Normal cluster operation</li><li>Possible RBAC enumeration attack — someone probing what they can access</li><li>API server restart</li><li>Pod crashes</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. RBAC enumeration.</strong> An unusual spike in 403 (Forbidden) responses suggests someone systematically trying to access resources they cannot — reconnaissance before an attack. Alert on this in Prometheus.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q6: What does etcd_server_has_leader = 0 indicate?</h5><ol><li>Everything is normal</li><li>etcd has lost its leader — cluster may be in read-only state, critical alert</li><li>etcd is upgrading</li><li>New leader elected</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Leader loss = cluster at risk.</strong> etcd uses Raft consensus. Without a leader, no writes can be committed. This metric dropping to 0 means the cluster state cannot change — potentially a full outage.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q7: Why does Fluent Bit run as a DaemonSet?</h5><ol><li>For high availability</li><li>One Fluent Bit pod per node collects ALL container logs on that node through the shared filesystem</li><li>For load balancing</li><li>Kubernetes requires DaemonSets for logging</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Per-node log collection.</strong> DaemonSet ensures exactly one Fluent Bit pod per node. It reads container logs from /var/log/containers on the host, processes them, and ships to Loki/ELK/Splunk.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q8: What is the observability triad for security?</h5><ol><li>CPU, Memory, Disk</li><li>Logs (what happened), Metrics (how much/how often), Traces (the full request path)</li><li>Pods, Services, Deployments</li><li>Input, Processing, Output</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Logs + Metrics + Traces.</strong> Logs = forensic record (audit logs). Metrics = anomaly detection (Prometheus alerts). Traces = lateral movement detection (follow requests across services). Together = complete security visibility.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q9: Which Falco alert output destination supports Slack notifications?</h5><ol><li>Falco stdout</li><li>Falco Sidekick — forwards alerts to Slack, PagerDuty, AWS SNS, and 30+ other destinations</li><li>Falco syslog output</li><li>Falco file output</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Falco Sidekick.</strong> Sidekick is a companion service that receives Falco alerts (via gRPC) and forwards them to Slack, PagerDuty, Opsgenie, AWS SNS/S3, Datadog, Elasticsearch, and dozens of other platforms.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q10: What does container_cpu_usage_seconds_total spike indicate?</h5><ol><li>Normal workload scaling</li><li>Possible cryptominer deployed — sudden sustained CPU spike with no code change is a strong indicator</li><li>Network latency increase</li><li>Memory leak</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Possible cryptomining.</strong> Sudden, sustained CPU spikes in containers with no deployment change strongly suggest cryptomining malware. Combine with Falco rules detecting unexpected process execution for confirmation.</p></details></div>')
Add-ChapterQs 20 $q

# Ch21: +7 - Service Mesh
$q=@()
$q+=,@('                    <div class="drill-scenario"><h5>Q4: What is the difference between Istio STRICT and PERMISSIVE mTLS modes?</h5><ol><li>No difference</li><li>STRICT = only mTLS allowed; PERMISSIVE = accepts both mTLS and plaintext — for migration only</li><li>PERMISSIVE is more secure</li><li>STRICT is deprecated</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. STRICT = mTLS only.</strong> STRICT mode: all connections must use mutual TLS. PERMISSIVE: accepts plaintext or mTLS for gradual migration. Always use STRICT in production after migration is complete.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q5: What is a SPIFFE identity in a service mesh?</h5><ol><li>An IP address</li><li>A cryptographically verifiable workload identity: spiffe://cluster.local/ns/namespace/sa/serviceaccount</li><li>A DNS name</li><li>A container ID</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Verifiable workload identity.</strong> SPIFFE IDs are bound to X.509 certificates by the mesh CA. When a pod presents its SPIFFE identity via mTLS, the receiver cryptographically verifies it. Authorization policies use SPIFFE IDs, not IPs.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q6: What does an Istio AuthorizationPolicy with action: DENY do?</h5><ol><li>Allows all traffic</li><li>Explicitly denies matching traffic — overrides any ALLOW policies</li><li>Logs traffic only</li><li>Ignores the traffic</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Explicit deny overrides allows.</strong> DENY policies take precedence over ALLOW policies in Istio. Use DENY to block specific dangerous patterns (e.g., DELETE on /jobs/) even if a broader ALLOW policy would permit it.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q7: Which service mesh is simplest to set up with automatic mTLS?</h5><ol><li>Istio</li><li>Linkerd — Rust-based proxy, auto-mTLS, minimal configuration</li><li>Consul Connect</li><li>All are equally complex</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Linkerd.</strong> Linkerd is designed for simplicity — auto-mTLS without configuration, lightweight Rust proxy, and minimal operational overhead. Istio offers more features but higher complexity.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q8: What is the Ambient Mesh in Istio?</h5><ol><li>A different product</li><li>Sidecar-less service mesh using node-level proxies — no sidecar injection per pod</li><li>A monitoring tool</li><li>A deployment strategy</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Sidecar-less mesh.</strong> Istio Ambient Mesh replaces per-pod sidecars with per-node ztunnel proxies (L4) and waypoint proxies (L7). Reduces resource usage and simplifies operations by removing sidecar injection entirely.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q9: How does a service mesh provide observability for security?</h5><ol><li>It does not provide observability</li><li>Kiali visualizes traffic flows; Jaeger traces requests across services; Grafana shows mesh metrics — detecting anomalies and lateral movement</li><li>Only through logs</li><li>Only through manual inspection</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Traffic visualization + tracing.</strong> Kiali shows which services are talking to which. Jaeger traces individual requests across all services. Together they detect unexpected communication patterns indicating compromise.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q10: What does enabling STRICT mTLS across the mesh prevent?</h5><ol><li>All network traffic</li><li>Man-in-the-middle attacks between services — all inter-pod traffic is encrypted and authenticated</li><li>Pod creation</li><li>Service discovery</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. MITM prevention.</strong> STRICT mTLS ensures every pod-to-pod connection is both encrypted AND authenticated. An attacker cannot eavesdrop or inject traffic even if they compromise the underlying network.</p></details></div>')
Add-ChapterQs 21 $q

# Ch22: +7 - PKI & Certs
$q=@()
$q+=,@('                    <div class="drill-scenario"><h5>Q4: What happens when the kube-apiserver certificate expires?</h5><ol><li>Nothing — auto-renews</li><li>kubectl stops working — ALL API access fails. Cluster is effectively down</li><li>Only new pods fail</li><li>Only etcd connections fail</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. kubectl fails.</strong> If the API server TLS certificate expires, ALL kubectl commands fail with x509 errors. Set Prometheus alerts at 30, 14, and 7 days before expiry. cert-manager auto-renews application certs but not control plane certs.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q5: How does cert-manager handle certificate renewal?</h5><ol><li>Requires manual intervention</li><li>Automatically renews certificates 30 days before expiry — creates new CertificateRequest, fulfills via ACME, updates Secret</li><li>Deletes and recreates certificates</li><li>Sends email reminders</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Automatic renewal.</strong> cert-manager monitors Certificate resources and auto-renews 30 days before expiry. It creates a CertificateRequest, fulfills via ACME/CA/Vault, and updates the referenced Secret — zero downtime.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q6: Why should etcd have a separate CA from the cluster CA?</h5><ol><li>Required by CNCF rules</li><li>Compromise containment — if the cluster CA is breached, etcd certificates remain secure (and vice versa)</li><li>Better performance with separate CAs</li><li>etcd does not use certificates</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Compromise containment.</strong> Separate CAs for etcd, kubelet, and front-proxy limit blast radius. A compromised cluster CA cannot forge etcd peer certificates to disrupt Raft consensus.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q7: What does the ACME HTTP-01 challenge verify?</h5><ol><li>DNS ownership</li><li>That you control the web server at the domain by placing a specific file at /.well-known/acme-challenge/</li><li>Email ownership</li><li>IP address ownership</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Web server control.</strong> HTTP-01 challenge proves domain control by placing a token file at a specific URL path. DNS-01 alternative proves control via DNS TXT record. Use DNS-01 for wildcard certificates.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q8: What is the default expiry for kubeadm-generated certificates?</h5><ol><li>90 days</li><li>1 year — must manually renew or configure auto-renewal</li><li>5 years</li><li>Never expire</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. 1 year.</strong> kubeadm certificates (API server, etcd, kubelet) expire after 1 year. Check with kubeadm certs check-expiration. Renew with kubeadm certs renew all. Automate renewal in production.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q9: Which cert-manager resource is namespace-scoped vs cluster-wide?</h5><ol><li>Both are cluster-wide</li><li>Issuer is namespace-scoped; ClusterIssuer is cluster-wide — any namespace can use a ClusterIssuer</li><li>Issuer is cluster-wide; ClusterIssuer is namespace-scoped</li><li>Both are namespace-scoped</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Issuer=namespace, ClusterIssuer=cluster.</strong> Use ClusterIssuer for shared ACME (Let''s Encrypt) setup so all namespaces can request certificates. Use Issuer for namespace-specific CAs.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q10: Why should you use short-lived certificates (90 days or less)?</h5><ol><li>They are faster to generate</li><li>Limits damage window if a private key is compromised — cert expires quickly, attacker loses access</li><li>Kubernetes requires short-lived certs</li><li>They use less disk space</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Damage containment.</strong> Short-lived certs limit the exposure window. If a private key is stolen, the certificate expires in 90 days (or less). Combine with cert-manager auto-renewal for zero-touch rotation.</p></details></div>')
Add-ChapterQs 22 $q

# Ch23: +7 - Compliance
$q=@()
$q+=,@('                    <div class="drill-scenario"><h5>Q4: If anihpj processes credit card payments, which framework applies?</h5><ol><li>SOC 2</li><li>PCI-DSS — requires encryption, segmentation, access control, and audit logging for cardholder data</li><li>GDPR</li><li>ISO 27001</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. PCI-DSS.</strong> Payment Card Industry Data Security Standard applies to ANY system handling cardholder data. Requires NetworkPolicy segmentation, EncryptionConfiguration, RBAC, and audit logging.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q5: What does SOC 2 audit for service organizations?</h5><ol><li>Only financial controls</li><li>Five Trust Service Criteria: Security, Availability, Confidentiality, Processing Integrity, Privacy</li><li>Only network security</li><li>Only data encryption</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Five trust criteria.</strong> SOC 2 evaluates security, availability, processing integrity, confidentiality, and privacy. K8s mapping: RBAC (security), HA clusters (availability), NetworkPolicies (confidentiality).</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q6: What is the difference between Kubescape and kube-bench?</h5><ol><li>No difference</li><li>Kubescape scans against NSA, MITRE, PCI-DSS, GDPR; kube-bench is CIS Benchmark only</li><li>kube-bench covers more frameworks</li><li>Kubescape is CIS-only</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Multi-framework vs CIS-only.</strong> Kubescape checks against multiple frameworks and generates compliance PDFs. kube-bench specifically tests the CIS Kubernetes Benchmark (100+ controls) with PASS/FAIL/WARN output.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q7: What is the shared responsibility model for compliance in managed K8s?</h5><ol><li>Customer handles everything</li><li>Cloud provider certifies control plane (FedRAMP/SOC2); customer certifies their workloads (RBAC, encryption, audit)</li><li>Cloud provider handles all compliance</li><li>CNCF certifies the cluster</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Split responsibility.</strong> AWS/Azure/GCP certify the managed control plane. YOU must certify: pod security, RBAC, NetworkPolicies, etcd encryption, audit logging, and your application security controls.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q8: What does GDPR require for personal data breach notification?</h5><ol><li>No notification required</li><li>Notify supervisory authority within 72 hours of becoming aware of the breach</li><li>Notify within 30 days</li><li>Only notify if data is financial</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. 72-hour notification.</strong> GDPR Article 33 requires notifying the relevant data protection authority within 72 hours of discovering a personal data breach. This makes audit logging and incident detection critical for compliance.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q9: Which tool verifies a single CIS Benchmark control?</h5><ol><li>Kubescape</li><li>kube-bench run --check="1.1.1" — runs a specific CIS control</li><li>Falco</li><li>OPA</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. kube-bench with --check.</strong> kube-bench can target individual CIS controls (e.g., 1.1.1 for API server audit log). Kubescape checks whole frameworks. Falco monitors runtime. OPA enforces policies.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q10: What is compliance as code?</h5><ol><li>Writing compliance reports manually</li><li>Encoding compliance requirements as machine-enforceable policies (OPA Rego / Kyverno YAML) stored in Git with automated drift detection</li><li>A specific tool name</li><li>Compliance without policies</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Policy-as-code in Git.</strong> Compliance as code means writing policies (e.g., all pods must have resource limits for SOC 2) as Kyverno/OPA rules in Git. GitOps enforces them. Drift detection alerts on manual changes. Auditor sees git history as evidence.</p></details></div>')
Add-ChapterQs 23 $q

# Ch24: +7 - Threat Modeling Frameworks
$q=@()
$q+=,@('                    <div class="drill-scenario"><h5>Q4: What is the 5-step threat modeling process?</h5><ol><li>Scan -> Patch -> Monitor -> Report -> Repeat</li><li>Scope -> Decompose -> Identify (STRIDE) -> Score (DREAD) -> Mitigate</li><li>Build -> Test -> Deploy -> Monitor -> Scale</li><li>Plan -> Code -> Build -> Test -> Release</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Scope->Decompose->Identify->Score->Mitigate.</strong> 1.Define scope (assets), 2.Decompose (data flows, boundaries), 3.Identify threats (STRIDE per component), 4.Analyze/score (DREAD), 5.Define countermeasures.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q5: What does the T in STRIDE stand for and how is it mitigated in K8s?</h5><ol><li>Trust — mitigated by NetworkPolicies</li><li>Tampering — mitigated by image signing (Cosign), admission control, and readOnlyRootFilesystem</li><li>Threat — mitigated by Falco</li><li>Token — mitigated by RBAC</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Tampering.</strong> Tampering = unauthorized modification. K8s mitigations: Cosign for image integrity, admission webhooks preventing unauthorized changes, readOnlyRootFilesystem blocking container filesystem writes.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q6: MITRE ATT&CK: T1610 (Deploy Container) maps to which tactic?</h5><ol><li>Execution</li><li>Initial Access — attacker deploys a malicious container to gain foothold</li><li>Persistence</li><li>Discovery</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Initial Access.</strong> T1610 (Deploy Container) is an Initial Access technique where an attacker deploys their own malicious container. Mitigate with admission control (Kyverno/OPA) and registry restrictions.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q7: What does the R in STRIDE represent and how is it mitigated?</h5><ol><li>Risk — mitigated by DREAD</li><li>Repudiation — mitigated by audit logging that proves who did what</li><li>Recovery — mitigated by backups</li><li>Reconnaissance — mitigated by NetworkPolicies</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Repudiation.</strong> Repudiation = denying an action was performed. Mitigated by comprehensive audit logging (who, what, when, where) with immutable storage. Audit logs provide non-repudiation.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q8: What DREAD score would trigger immediate remediation?</h5><ol><li>Any score above 0</li><li>Total score above 30/50 — indicates high damage, reproducibility, exploitability, many users affected, and easy discoverability</li><li>Only score of 50</li><li>Score doesn''t matter for prioritization</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Score above 30 = immediate fix.</strong> DREAD ≥ 30 = high priority. 40+ = critical (all users, severe damage, easy to exploit). 20-30 = fix soon. Under 20 = monitor. Use scoring to prioritize limited remediation resources.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q9: How does MITRE ATT&CK Container matrix help with K8s defense?</h5><ol><li>It lists software bugs</li><li>Maps real attacker techniques to specific K8s mitigations — each technique has documented detection and prevention methods</li><li>It is a compliance checklist</li><li>It is a scoring system</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Attack-to-defense mapping.</strong> MITRE ATT&CK for Containers maps 9 tactics and 40+ techniques to specific K8s controls. For each technique, it documents: how attackers do it, how to detect it (Falco rules), and how to prevent it (PSS, RBAC, NetworkPolicy).</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q10: What is the difference between an attack vector and attack surface?</h5><ol><li>Same thing — interchangeable</li><li>Attack vector = PATH an attacker takes to compromise (e.g., exposed API). Attack surface = ALL possible entry points combined</li><li>Attack surface is the path; vector is all points</li><li>Neither concept applies to K8s</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Path vs total area.</strong> Attack vector = specific path (e.g., compromised CI pipeline). Attack surface = sum of all vectors (API server, kubelet, etcd, pods, registry, supply chain). Minimize attack surface by removing unnecessary components.</p></details></div>')
Add-ChapterQs 24 $q

# Ch25: +7 - Supply Chain Compliance
$q=@()
$q+=,@('                    <div class="drill-scenario"><h5>Q4: What does Executive Order 14028 require for US government software?</h5><ol><li>Open source only</li><li>SBOM (Software Bill of Materials) and secure development attestation</li><li>Written in Rust</li><li>No third-party dependencies</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. SBOM + attestation.</strong> EO 14028 mandates SBOMs for all software sold to the US federal government, plus attestation of secure development practices. This drove the industry-wide adoption of SBOM standards.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q5: What does the EU Cyber Resilience Act require?</h5><ol><li>Only encryption</li><li>Security by design, SBOMs, vulnerability disclosure, and 5-year security support for all software products</li><li>Only documentation</li><li>Only incident reporting</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Full lifecycle security.</strong> EU CRA mandates: security by design/default, SBOM generation, vulnerability disclosure process, and minimum 5-year security support. Phased rollout through 2027. Applies to ALL software sold in EU.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q6: What is drift detection in GitOps compliance?</h5><ol><li>Detecting network latency drift</li><li>Detecting when live cluster configuration differs from the Git source of truth</li><li>Detecting memory leaks</li><li>Detecting pod restarts</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Configuration drift from Git.</strong> In GitOps, Git is the single source of truth. Drift detection (ArgoCD, Flux, Kubescape) alerts when someone manually changes something on the cluster — critical for audit compliance.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q7: What evidence does a Rekor transparency log provide?</h5><ol><li>Vulnerability scan results</li><li>Immutable, timestamped proof of who signed what artifact and when — cannot be altered retroactively</li><li>Compliance report</li><li>SBOM inventory</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Immutable signing proof.</strong> Rekor stores cryptographically verifiable records of every artifact signing. The log is append-only — once recorded, entries cannot be modified. Provides auditor-ready proof of supply chain integrity.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q8: What should a compliance evidence package contain for auditors?</h5><ol><li>Only a checklist</li><li>Kubescape PDF report + kube-bench CIS score + SBOM archive + Rekor signing log + Git change history</li><li>Only the audit log</li><li>Only a self-assessment</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Multi-source evidence.</strong> Complete package: framework compliance report (Kubescape), CIS benchmark score (kube-bench), dependency inventory (SBOM archive), signing proof (Rekor log), change history (Git). Automated, timestamped, immutable.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q9: How does continuous compliance differ from point-in-time audits?</h5><ol><li>Same thing</li><li>Continuous compliance runs automated checks constantly — not just before an audit. Drift is detected immediately</li><li>Point-in-time is more reliable</li><li>Continuous is less secure</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Always-on verification.</strong> Point-in-time audits check compliance once (e.g., annually). Continuous compliance runs automated scans daily/hourly — detecting non-compliance immediately, not months later when auditors arrive.</p></details></div>')
$q+=,@('                    <div class="drill-scenario"><h5>Q10: What is the complete supply chain security automation pipeline?</h5><ol><li>Only image scanning</li><li>Commit -> SBOM (Syft) -> Vuln scan (Trivy) -> Sign (Cosign) -> Provenance (SLSA) -> Admission verify (Kyverno)</li><li>Only image signing</li><li>Only admission control</li></ol></div>','                    <div class="drill-solution"><details><summary>✅ Answer</summary><p><strong>Answer: 2. Full automated pipeline.</strong> Every commit triggers: SBOM generation (Syft), vulnerability scanning (Trivy/Grype), image signing (Cosign with OIDC), SLSA provenance generation, and admission control verification (Kyverno). Fully automated, no manual steps.</p></details></div>')
Add-ChapterQs 25 $q

[System.IO.File]::WriteAllText((Resolve-Path $f), $c)
Write-Host "Ch18-25 done. File size: $([math]::Round($c.Length/1024,1))KB"